import type { AskMaraContext } from "./context";
import { findGlossaryEntry } from "./glossary";

export interface AskMaraAnswer { title: string; body: string; provenance: string }
const unavailable: AskMaraAnswer = { title: "Extended answer unavailable", body: "MARA's extended assistant is not configured in this environment yet. I can still explain Adaptara terms and the portfolio facts currently available here.", provenance: "Bounded assistant · no external model used" };

export function answerAskMara(question: string, context: AskMaraContext): AskMaraAnswer {
  const q = question.toLowerCase();
  if ((q.includes("my risk") || q.includes("current risk")) && !q.includes("mean")) return { title: "Current measured risk", body: context.riskTier && context.riskScore ? `Adaptara's deterministic model currently classifies this portfolio as ${context.riskTier}, with a score of ${context.riskScore} out of 100. This uses demo/non-live signals and is not a return prediction.` : "A complete deterministic risk result is not available for the current portfolio context.", provenance: "Current deterministic risk context" };
  const glossary = findGlossaryEntry(question);
  if (glossary) return { title: glossary.term, body: glossary.definition, provenance: "Canonical Adaptara glossary" };
  if (q.includes("this page") || q.includes("where am i")) return { title: `${context.destination} explained`, body: context.destination === "Home" ? "Home summarizes your current status and directs you to the next useful step." : context.destination === "Portfolio" ? "Portfolio shows supported holdings, allocation, and deterministic risk evidence." : context.destination === "MARA" ? "MARA explains what may deserve attention and lets you explicitly request a bounded simulation." : "Safety shows the active owner-controlled rules and current deterministic compliance.", provenance: "Current dashboard destination" };
  if (q.includes("what do i own") || q.includes("holdings")) { const held = context.positions.filter((p) => p.allocationPercent !== null).map((p) => `${p.symbol} ${p.allocationPercent}`).join(", "); return { title: "Supported holdings", body: held ? `The current ${context.source} context contains: ${held}.` : "No complete supported allocation is available in the current context.", provenance: "Current deterministic portfolio context" }; }
  if (q.includes("risk")) return { title: "Current measured risk", body: context.riskTier && context.riskScore ? `Adaptara's deterministic model currently classifies this portfolio as ${context.riskTier}, with a score of ${context.riskScore} out of 100. This uses demo/non-live signals and is not a return prediction.` : "A complete deterministic risk result is not available for the current portfolio context.", provenance: "Current deterministic risk context" };
  if (q.includes("compliant") || q.includes("protected") || q.includes("rule")) return { title: "Current Constitution check", body: context.compliance === "compliant" ? "The fully valued portfolio currently satisfies the active rules checked by Adaptara. This is a deterministic result, not a guarantee against loss." : context.compliance === "violated" ? "One or more active Constitution rules are currently violated. Review Safety for the exact rule evidence." : "Compliance is unavailable until both a complete valuation and active policy are available.", provenance: "Current deterministic policy context" };
  if (/\b(buy|sell|swap|execute|approve|sign|transfer)\b/.test(q)) return { title: "No execution authority", body: "I cannot sign, move assets, submit transactions, or bypass your Financial Constitution. I can explain the current facts or help you review a simulation.", provenance: "Adaptara authority boundary" };
  return unavailable;
}
