import type{Metadata}from"next";import{PublicDocument}from"@/components/public/public-document";
export const metadata:Metadata={title:"Adaptara Docs",description:"How Adaptara provides policy-bounded personal adaptive portfolio management on X Layer."};
const P=({children}:{children:React.ReactNode})=><p>{children}</p>;
export default function Docs(){return <PublicDocument title="Adaptara Docs" subtitle="How personal portfolio intelligence becomes policy-bounded adaptive management." sections={[
{id:"overview",title:"Overview",body:<><P>Adaptara is a personal adaptive portfolio-management system. It begins with the wallet you already use, provides Intelligence Mode before custody, and manages only capital explicitly delegated into an owner-controlled Vault.</P><P>It is not a pooled treasury, APY aggregator, or unconstrained AI trader.</P></>},
{id:"getting-started",title:"Getting Started",body:<ol><li>Connect and analyze the existing wallet.</li><li>Create a Managed Vault and delegate selected capital.</li><li>Set the Financial Constitution.</li><li>Choose Advisory, Approval Required, or Adaptive.</li><li>Activate MARA only after explicit owner authorization.</li></ol>},
{id:"concepts",title:"Core Concepts",body:<><h3>Intelligence Mode</h3><P>Your wallet is analyzed; MARA cannot move its assets.</P><h3>Managed Mode</h3><P>Only Vault capital is governed by the managed mandate.</P><h3>Financial Constitution</h3><P>Owner rules cover reserve, concentration, aggressive exposure, action/turnover, slippage, assets, adapters, yield allocation, modes, pause and revocation.</P></>},
{id:"authority",title:"Authority Model",body:<dl><dt>Owner</dt><dd>Controls Vault and Constitution.</dd><dt>MARA</dt><dd>Observes and proposes direction.</dd><dt>Planner</dt><dd>Calculates exact amounts.</dd><dt>Constitution</dt><dd>Allows or blocks.</dd><dt>Executor</dt><dd>Submits restricted typed actions only.</dd><dt>Managed Vault</dt><dd>Verifies actual state and enforces post-state policy.</dd></dl>},
{id:"execution",title:"Portfolio Management & Execution",body:<><P>Market, news and portfolio observations inform MARA. Exact single-hop Uniswap V3 swaps and narrow Aave V3 supply/withdraw actions use protocol-supported and owner-enabled adapters. Actual balance deltas—not adapter claims—are authoritative. Policy failure atomically rolls back.</P><P>Yield is secondary: only eligible excess reserve may enter Aave, with owner-defined compound and liquid-reserve disposition.</P></>},
{id:"security",title:"Security",body:<><P>No LLM output becomes transaction authority. Missing or stale valuation, unavailable routes, paused Aave reserves, revoked executors and policy violations fail closed. Owners can pause Adaptive management and revoke the executor.</P></>},
{id:"status",title:"Current Status",body:<table><tbody><tr><th>Wallet intelligence</th><td>Implemented</td></tr><tr><th>Financial Constitution</th><td>Implemented</td></tr><tr><th>MARA and deterministic planning</th><td>Implemented</td></tr><tr><th>Uniswap V3</th><td>X Layer mainnet fork-proven</td></tr><tr><th>Aave V3 and yield accounting</th><td>Fork-proven / tested</td></tr><tr><th>Mainnet Adaptara deployment</th><td>Not deployed</td></tr><tr><th>Public autonomous execution</th><td>Disabled</td></tr></tbody></table>},
{id:"faq",title:"FAQ",body:<><h3>Can MARA access my wallet?</h3><P>No. Only explicitly delegated Vault capital can enter the managed mandate.</P><h3>Is yield guaranteed?</h3><P>No. Protocol rates are variable and strategies remain bounded by policy.</P><h3>Is Adaptara live?</h3><P>The architecture is implemented and fork-proven; Adaptara contracts are not publicly deployed and autonomous broadcast is disabled.</P></>}
]}/>}
