import { describe, expect, it, vi } from "vitest";
import type { PublicClient, WalletClient } from "viem";
import { createAssetCatalog } from "@/features/portfolio/catalog";
import { updateVaultConstitution } from "./writers";
const owner="0x0000000000000000000000000000000000000001" as const, other="0x0000000000000000000000000000000000000003" as const, vault="0x0000000000000000000000000000000000000002" as const, hash=`0x${"1".repeat(64)}` as const;
const policy={minimumReserveBps:4000,maximumSingleAssetExposureBps:4000,maximumAggressiveExposureBps:2000,maximumDailyReallocationBps:500};
const publicClient=(overrides={})=>({getChainId:vi.fn().mockResolvedValue(1952),getBlockNumber:vi.fn().mockResolvedValue(42n),readContract:vi.fn(async({functionName})=>functionName==="owner"?owner:[4000,4000,2000,500]),waitForTransactionReceipt:vi.fn().mockResolvedValue({status:"success",blockNumber:43n}),...overrides}) as unknown as PublicClient;
const wallet=(overrides={})=>({chain:{id:1952},writeContract:vi.fn().mockResolvedValue(hash),...overrides}) as unknown as WalletClient;
describe("owner constitution write",()=>{
 it("uses only setPolicy values and waits before rereading",async()=>{const pub=publicClient(), w=wallet(); const result=await updateVaultConstitution({publicClient:pub,walletClient:w,vaultAddress:vault,connectedAddress:owner,policy,assets:createAssetCatalog()}); expect(w.writeContract).toHaveBeenCalledWith(expect.objectContaining({address:vault,functionName:"setPolicy",args:[policy]})); expect(pub.waitForTransactionReceipt).toHaveBeenCalledWith({hash}); expect(result.constitution.source).toBe("onchain");});
 it("rejects wrong chain before write",async()=>{const w=wallet(); await expect(updateVaultConstitution({publicClient:publicClient({getChainId:vi.fn().mockResolvedValue(1)}),walletClient:w,vaultAddress:vault,connectedAddress:owner,policy,assets:createAssetCatalog()})).rejects.toThrow("X Layer"); expect(w.writeContract).not.toHaveBeenCalled();});
 it("rejects non-owner before write",async()=>{const w=wallet(); await expect(updateVaultConstitution({publicClient:publicClient(),walletClient:w,vaultAddress:vault,connectedAddress:other,policy,assets:createAssetCatalog()})).rejects.toThrow("not the vault owner"); expect(w.writeContract).not.toHaveBeenCalled();});
 it("rejects a mismatched wallet client account before write",async()=>{const w=wallet({account:{address:other}}); await expect(updateVaultConstitution({publicClient:publicClient(),walletClient:w,vaultAddress:vault,connectedAddress:owner,policy,assets:createAssetCatalog()})).rejects.toThrow("does not match"); expect(w.writeContract).not.toHaveBeenCalled();});
 it("rejects invalid and infeasible policies",async()=>{const w=wallet(); await expect(updateVaultConstitution({publicClient:publicClient(),walletClient:w,vaultAddress:vault,connectedAddress:owner,policy:{...policy,minimumReserveBps:10001},assets:createAssetCatalog()})).rejects.toThrow("integer"); await expect(updateVaultConstitution({publicClient:publicClient(),walletClient:w,vaultAddress:vault,connectedAddress:owner,policy:{...policy,minimumReserveBps:6000},assets:createAssetCatalog()})).rejects.toThrow("cannot currently satisfy"); expect(w.writeContract).not.toHaveBeenCalled();});
 it("does not report a failed receipt as success",async()=>{await expect(updateVaultConstitution({publicClient:publicClient({waitForTransactionReceipt:vi.fn().mockResolvedValue({status:"reverted",blockNumber:43n})}),walletClient:wallet(),vaultAddress:vault,connectedAddress:owner,policy,assets:createAssetCatalog()})).rejects.toThrow("failed onchain");});
 it("reports confirmed-but-reread-failed distinctly",async()=>{const getBlockNumber=vi.fn().mockResolvedValueOnce(42n).mockRejectedValueOnce(new Error("post-confirmation RPC failed")); await expect(updateVaultConstitution({publicClient:publicClient({getBlockNumber}),walletClient:wallet(),vaultAddress:vault,connectedAddress:owner,policy,assets:createAssetCatalog()})).rejects.toThrow("Transaction confirmed, but the onchain constitution reread failed: post-confirmation RPC failed");});
});
