import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { QueryClient } from "@tanstack/react-query";
import { createAssetCatalog } from "@/features/portfolio/catalog";
import type { AssetPosition, PortfolioSnapshot } from "@/features/portfolio/types";
import type { FinancialConstitution, OnchainConstitution } from "../types";
import { activeConstitutionOrNull, applyConfirmedConstitution, canSubmitConstitution, commitConfirmedConstitution, ConstitutionComplianceSection, ConstitutionSourceBadge, ConstitutionWriteControl, constitutionContextId, executeConstitutionWriteIfEnabled, freshConstitutionContextState, PolicyReadStatus, shouldShowPolicyControls } from "./financial-constitution";

const catalog=createAssetCatalog();
const position=(index:number,allocationBps:number):AssetPosition=>({asset:catalog[index],availability:"available",rawBalance:1n,balanceDecimals:18,displayBalance:"1",referencePrice:null,usdValue:1n,usdValueDecimals:8,allocationBps});
const snapshot={source:"vault",accountAddress:"0x0000000000000000000000000000000000000001",chainId:1952,blockNumber:1n,blockConsistency:"single-block",capturedAt:"2026-01-01T00:00:00Z",positions:[position(0,4000),position(1,6000)],totals:{totalUsdValue:2n,usdValueDecimals:8,valuedAssetCount:2,nonzeroAssetCount:2,unknownBalanceAssetCount:0},valuationStatus:"valued",priceSources:["fixture"]} satisfies PortfolioSnapshot;
const active:FinancialConstitution={minimumReserveBps:3000,maximumSingleAssetExposureBps:7000,maximumAggressiveExposureBps:1000,maximumDailyReallocationBps:500};
const draft:FinancialConstitution={...active,minimumReserveBps:5000};
const walletA="0x0000000000000000000000000000000000000001" as const, walletB="0x0000000000000000000000000000000000000003" as const, vaultA="0x0000000000000000000000000000000000000002" as const, vaultB="0x0000000000000000000000000000000000000004" as const;
const confirmed=(constitution=draft):OnchainConstitution=>({version:"phase-6.v1",source:"onchain",constitution,vaultAddress:vaultA,owner:walletA,blockNumber:43n,capturedAt:"2026-01-01T00:00:01Z"});

describe("Financial Constitution presentation",()=>{
 it("keeps active compliance based on onchain policy while an edited draft would differ",()=>{const activeHtml=renderToStaticMarkup(<ConstitutionComplianceSection snapshot={snapshot} policy={active} draftPreview={false}/>); const draftHtml=renderToStaticMarkup(<ConstitutionComplianceSection snapshot={snapshot} policy={draft} draftPreview={false}/>); expect(activeHtml).toContain("Compliant"); expect(activeHtml).not.toContain("Violated"); expect(draftHtml).toContain("Violated");});
 it("shows dirty unsaved state",()=>expect(renderToStaticMarkup(<PolicyReadStatus blockNumber={42n} dirty/>)).toContain("Unsaved changes"));
 it("labels no-vault compliance as a non-active draft preview",()=>{const html=renderToStaticMarkup(<ConstitutionComplianceSection snapshot={snapshot} policy={draft} draftPreview/>); expect(html).toContain("Draft Portfolio Compliance Preview"); expect(html).toContain("not active onchain");});
 it("does not label a loading vault policy as active",()=>{const html=renderToStaticMarkup(<ConstitutionSourceBadge hasVault pending failed={false} loaded={false}/>); expect(html).toContain("Loading onchain constitution"); expect(html).not.toContain(">Onchain constitution<");});
 it("does not label a failed vault policy read as active",()=>{const html=renderToStaticMarkup(<ConstitutionSourceBadge hasVault pending={false} failed loaded={false}/>); expect(html).toContain("Onchain constitution unavailable"); expect(html).not.toContain(">Onchain constitution<");});
 it("labels a successful policy read as onchain",()=>expect(renderToStaticMarkup(<ConstitutionSourceBadge hasVault pending={false} failed={false} loaded/>)).toContain(">Onchain constitution<"));
 it("labels a zero onchain policy as not activated",()=>{const html=renderToStaticMarkup(<ConstitutionSourceBadge hasVault pending={false} failed={false} loaded activated={false}/>); expect(html).toContain("Not activated"); expect(html).toContain("zero onchain policy");});
 it("uses active-policy-unavailable compliance messaging when policy is missing",()=>{const html=renderToStaticMarkup(<ConstitutionComplianceSection snapshot={snapshot} policy={undefined} draftPreview={false}/>); expect(html).toContain("active onchain constitution is unavailable"); expect(html).not.toContain("valuation is complete");});
 it("applies the confirmed returned constitution to active and draft state",()=>{const value=confirmed(); const next=applyConfirmedConstitution(value); expect(next.active).toBe(value); expect(next.draft).toBe(draft); expect(next.inputs.minimumReserveBps).toBe("50.00");});
 it("resets Vault A state to a fresh no-vault draft and preview",()=>{const fresh=freshConstitutionContextState(); expect(fresh.draft).toEqual({minimumReserveBps:0,maximumSingleAssetExposureBps:0,maximumAggressiveExposureBps:0,maximumDailyReallocationBps:0}); expect(JSON.stringify(fresh)).not.toContain("5000"); const badge=renderToStaticMarkup(<ConstitutionSourceBadge hasVault={false} pending={false} failed={false} loaded={false}/>); const preview=renderToStaticMarkup(<ConstitutionComplianceSection snapshot={snapshot} policy={fresh.draft} draftPreview/>); expect(badge).toContain("Draft"); expect(preview).toContain("Draft Portfolio Compliance Preview");});
 it("hides Vault A controls after switching to loading Vault B",()=>{expect(constitutionContextId(walletA,vaultA)).not.toBe(constitutionContextId(walletB,vaultB)); expect(shouldShowPolicyControls(true,false)).toBe(false); expect(renderToStaticMarkup(<ConstitutionSourceBadge hasVault pending failed={false} loaded={false}/>)).toContain("Loading onchain constitution");});
 it("clears an old transaction status on account change",()=>expect(freshConstitutionContextState()).toMatchObject({tx:"",saving:false,errors:{}}));
 it("keeps a late Wallet A result out of Wallet B visible state while caching A",()=>{const queryClient=new QueryClient(); const key=["financial-constitution",walletA,vaultA] as const; const value=confirmed(); const visible=commitConfirmedConstitution(queryClient,key,value,constitutionContextId(walletA,vaultA),constitutionContextId(walletB,vaultB)); expect(visible).toBeNull(); expect(queryClient.getQueryData(key)).toBe(value);});
 it("same-context save updates React Query, draft inputs, and confirmed state",()=>{const queryClient=new QueryClient(); const key=["financial-constitution",walletA,vaultA] as const; const value=confirmed(); const context=constitutionContextId(walletA,vaultA); const visible=commitConfirmedConstitution(queryClient,key,value,context,context); expect(queryClient.getQueryData(key)).toBe(value); expect(visible).toMatchObject({active:value,draft:value.constitution,inputs:{minimumReserveBps:"50.00"}});});
 it("defaults the Phase 12C1 capability calculation to non-writing even when every owner condition is ready",()=>{expect(canSubmitConstitution({writesEnabled:false,hasVault:true,policyLoaded:true,hasWalletClient:true,owner:true,dirty:true,valid:true,feasible:true,hasErrors:false,saving:false})).toBe(false);});
 it("cannot submit without a connected wallet client even if a future phase enables writes",()=>{expect(canSubmitConstitution({writesEnabled:true,hasVault:true,policyLoaded:true,hasWalletClient:false,owner:true,dirty:true,valid:true,feasible:true,hasErrors:false,saving:false})).toBe(false);});
 it("renders truthful read-only copy instead of an activation button",()=>{const html=renderToStaticMarkup(<ConstitutionWriteControl writesEnabled={false} canSave={false} saving={false} onSave={()=>{}}/>); expect(html).toContain("not enabled during read-only deployment verification"); expect(html).not.toContain("Save Constitution Onchain");});
 it("does not touch the transaction operation when writes are disabled",async()=>{const transaction=vi.fn().mockResolvedValue("sent"); await expect(executeConstitutionWriteIfEnabled(false,transaction)).resolves.toBeNull(); expect(transaction).not.toHaveBeenCalled();});
 it("exposes only genuinely activated policies downstream",()=>{expect(activeConstitutionOrNull(confirmed({minimumReserveBps:0,maximumSingleAssetExposureBps:0,maximumAggressiveExposureBps:0,maximumDailyReallocationBps:0}))).toBeNull(); const value=confirmed(); expect(activeConstitutionOrNull(value)).toBe(value);});
 it("clears downstream active state on a context switch or missing current result",()=>{expect(constitutionContextId(walletA,vaultA)).not.toBe(constitutionContextId(walletB,vaultB)); expect(activeConstitutionOrNull(undefined)).toBeNull();});
 it("keeps a late zero-policy result from becoming active Adaptation authority",()=>{const late=confirmed({minimumReserveBps:0,maximumSingleAssetExposureBps:0,maximumAggressiveExposureBps:0,maximumDailyReallocationBps:0}); expect(activeConstitutionOrNull(late)).toBeNull();});
});
