export function ProductHero() {
  return <section className="grid gap-8 py-12 lg:grid-cols-[1.35fr_.65fr] lg:items-end lg:py-16"><div><p className="eyebrow">Adaptara</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-[1.05] tracking-[-0.04em] sm:text-6xl">Adaptive intelligence for onchain wealth.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--muted)] sm:text-lg">Understand risk, define your rules, and explore adaptive onchain wealth strategies without giving AI unrestricted control of your assets.</p></div><aside className="trust-callout" aria-label="Adaptara authority model"><span className="eyebrow">The authority boundary</span><p className="mt-3 text-xl font-semibold leading-8">AI decides what should happen.<br />X Layer guarantees what is allowed to happen.</p></aside></section>;
}
export function SystemExplainer() {
  const steps = ["Observe", "Assess", "Interpret", "Simulate", "Validate"];
  return <section className="section-card" aria-labelledby="system-title"><div className="section-heading"><div><p className="eyebrow">How Adaptara works</p><h2 id="system-title">Intelligence with a hard boundary</h2></div><span className="status-badge status-neutral">Execution · future / not enabled</span></div><ol className="workflow" aria-label="Adaptara workflow">{steps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></li>)}</ol><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="subtle-panel"><h3>Deterministic by design</h3><p>Portfolio valuation, current measured risk, policy checks, and simulations are calculated by deterministic engines.</p></div><div className="subtle-panel"><h3>User-controlled authority</h3><p>MARA is advisory only. The user defines the Financial Constitution, and smart-contract policy is the authority boundary. Adaptation and yield remain simulation-only.</p></div></div></section>;
}
export function AppFooter() { return <footer className="flex flex-col gap-2 border-t border-[var(--line)] py-8 text-sm text-[var(--muted)] sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-[var(--foreground)]">Adaptara</strong> · Adaptive intelligence for onchain wealth.</div><div>X Layer Testnet · Demo and sandbox data where labeled · No real investment value</div></footer>; }
export function EnvironmentStrip() { return <div className="environment-strip"><span className="status-badge status-success">X Layer Testnet</span><span>Demo/non-live reference inputs</span><span>Sandbox RWA assets have no redemption rights</span></div>; }
