import type { MarketSignal, NewsSignal, ObservationCycleResult, PortfolioExposure, ProposedSwapIntentV1, RelevantSignal, MarketObservationProvider, NewsObservationProvider } from "./types";

const current = (expiresAt: string, now: Date) => Date.parse(expiresAt) >= now.getTime();
export function marketRelevance(signal: MarketSignal, portfolio: PortfolioExposure[]): RelevantSignal<MarketSignal> | null { const exposure = portfolio.find((p) => p.assetId === signal.assetId); if (!exposure || (!exposure.held && !exposure.allowed)) return null; return { signal, relevanceBps: exposure.held ? Math.min(10_000, 4_000 + exposure.allocationBps) : 2_000, reason: exposure.held ? `Held exposure is ${exposure.allocationBps} BPS` : "Owner-allowed candidate asset" }; }
export function newsRelevance(signal: NewsSignal, portfolio: PortfolioExposure[]): RelevantSignal<NewsSignal> | null { const matches = portfolio.filter((p) => signal.relatedAssetIds.includes(p.assetId) && (p.held || p.allowed)); if (!matches.length) return null; const held = matches.filter((p) => p.held); return { signal, relevanceBps: held.length ? Math.min(10_000, 3_000 + Math.max(...held.map((p) => p.allocationBps))) : 1_500, reason: held.length ? "News relates to a managed holding" : "News relates to an owner-allowed candidate" }; }

export async function runObservationCycle(input: { portfolio: PortfolioExposure[]; managementMode: "Advisory" | "ApprovalRequired" | "Adaptive"; marketProvider: MarketObservationProvider; newsProvider: NewsObservationProvider; now: Date }): Promise<ObservationCycleResult> {
  const [marketBatch, newsBatch] = await Promise.all([input.marketProvider.observeMarket(input.portfolio, input.now), input.newsProvider.observeNews(input.portfolio, input.now)]);
  const market = marketBatch.observations.filter((s) => current(s.expiresAt, input.now)).map((s) => marketRelevance(s, input.portfolio)).filter((x): x is RelevantSignal<MarketSignal> => x !== null).sort((a,b) => b.relevanceBps-a.relevanceBps);
  const news = newsBatch.observations.filter((s) => current(s.expiresAt, input.now)).map((s) => newsRelevance(s, input.portfolio)).filter((x): x is RelevantSignal<NewsSignal> => x !== null).sort((a,b) => b.relevanceBps-a.relevanceBps);
  const adverseNews = news.find((x) => x.signal.sentiment === "bearish" && input.portfolio.some((p) => p.held && x.signal.relatedAssetIds.includes(p.assetId)));
  const adverseHeldAsset = adverseNews?.signal.relatedAssetIds.find((id) => input.portfolio.some((p) => p.assetId === id && p.held));
  const proposal: ProposedSwapIntentV1 | null = adverseNews && adverseHeldAsset ? { schemaVersion: "phase-13c.proposed-swap.v1", direction: "reduce", assetId: adverseHeldAsset, targetAllocationBps: null, rationale: "Evaluate reducing exposure; a deterministic planner must calculate any amount.", evidenceRefs: [adverseNews.signal.id], advisoryConfidence: "medium", expiresAt: adverseNews.signal.expiresAt, executionAuthority: "none", plannerRequired: true } : null;
  const limitations = [marketBatch.status === "unavailable" ? "Market provider unavailable; this is not a neutral signal." : null, newsBatch.status === "unavailable" ? "News provider unavailable; this is not no-news." : null].filter((x): x is string => x !== null);
  return { context: { contextVersion: "phase-13c.observation.v1", capturedAt: input.now.toISOString(), portfolio: input.portfolio, market: { status: marketBatch.status, signals: market }, news: { status: newsBatch.status, signals: news }, policy: { managementMode: input.managementMode, executionAuthority: "none" }, limitations }, proposal, summary: proposal ? "Current relevant evidence warrants a bounded, non-executing review proposal." : limitations.length ? "Observation is incomplete; unavailable sources were not treated as neutral." : "No current relevant adverse evidence produced a proposal." };
}
