import type{Metadata}from"next";import{PublicDocument}from"@/components/public/public-document";
export const metadata:Metadata={title:"Adaptara Whitepaper",description:"A policy-bounded autonomous portfolio management system on X Layer."};const P=({children}:{children:React.ReactNode})=><p>{children}</p>;
export default function Whitepaper(){return <PublicDocument title="Adaptara Whitepaper" subtitle="A Policy-Bounded Autonomous Portfolio Management System" sections={[
{id:"abstract",title:"Abstract",body:<P>Adaptara combines personal portfolio intelligence, selectively delegated capital, an enforceable Financial Constitution, MARA interpretation, deterministic planning, typed rebalancing and bounded yield management. Autonomy is constrained by owner policy and actual onchain state.</P>},
{id:"problem",title:"Problem & Response",body:<P>Manual management preserves control but demands attention; standardized products trade personalization for convenience; autonomous agents become dangerous when intelligence and transaction authority are merged. Adaptara responds with policy-bounded autonomy.</P>},
{id:"principles",title:"Design Principles",body:<ul><li>Owner sovereignty and delegated capital only</li><li>AI proposes; deterministic systems execute</li><li>Policy before action and actual state over claimed state</li><li>Fail closed with no arbitrary execution surface</li><li>Transparent authority boundaries</li></ul>},
{id:"architecture",title:"Architecture",body:<pre>Existing Portfolio{"\n"}  ↓ Observation: Market · News · Portfolio{"\n"}  ↓ MARA: Interpretation / Direction{"\n"}  ↓ Deterministic Planner: Exact Amounts{"\n"}  ↓ Financial Constitution: Allow / Block{"\n"}  ↓ Typed Adapters: Uniswap · Aave{"\n"}  ↓ Managed Vault: Actual Balance Verification{"\n"}  ↓ Post-State Constitution</pre>},
{id:"constitution",title:"Financial Constitution",body:<P>The Constitution is a personalized onchain investment mandate covering liquid reserve, concentration, aggressive exposure, daily turnover, action size, slippage, approved assets and adapters, yield allocation and disposition, management mode, pause and revocation. MARA cannot change it.</P>},
{id:"mara",title:"MARA",body:<><blockquote>MARA has bounded hands, not sovereignty.</blockquote><P>MARA observes, interprets and proposes direction. It cannot modify policy, choose executable amounts, select arbitrary targets or calldata, control private keys, or access capital outside the Vault.</P></>},
{id:"execution",title:"Deterministic Execution",body:<P>Typed intents pass through deterministic planning, dual adapter authorization, exact approvals, real balance-delta verification and post-state validation. Any failed rule atomically rolls back. Execution paths remain narrow and typed.</P>},
{id:"rebalancing",title:"Adaptive Rebalancing",body:<P>The current implementation uses a direct single-hop Uniswap V3 adapter because opaque arbitrary routing would enlarge transaction authority.</P>},
{id:"yield",title:"Yield Management",body:<P>Eligible excess reserve may enter an approved Aave V3 supply strategy. Principal, accrued yield, retained yield and returned liquid reserve are separately accounted without double counting. There is no borrowing or leverage.</P>},
{id:"security",title:"Security Model",body:<P>Malicious MARA output, compromised executors and frontends remain constrained by contract policy and typed targets. Stale or missing oracles, wrong networks, malicious tokens, unavailable protocols and policy violations fail closed. Protocol administration cannot withdraw user funds.</P>},
{id:"evidence",title:"Fork Evidence",body:<><P>Uniswap proof uses the real X Layer Factory, QuoterV2, Router02 and pool; successful swaps clean allowances and custody, while Constitution violations roll back atomically.</P><P>Aave proof uses the real Pool and USDT reserve for supply, withdrawal, aToken accounting, yield settlement and policy rollback.</P></>},
{id:"limitations",title:"Current Limitations",body:<ul><li>Adaptara contracts are not publicly deployed.</li><li>Production valuation feeds are not finalized.</li><li>Executor custody and monitoring are not activated.</li><li>Autonomous mainnet broadcast is disabled.</li><li>Independent deployment security review remains pending.</li></ul>},
{id:"roadmap",title:"Roadmap",body:<P>Current: fork-proven portfolio architecture. Next: controlled deployment and wallet-authorized setup. Later: a broader asset universe and only carefully audited typed strategy adapters.</P>}
]}/>}
