import { describe, expect, it } from "vitest";
import { getAddress } from "viem";
import { createAssetCatalog } from "@/features/portfolio/catalog";
import type { AssetPosition, PortfolioSnapshot } from "@/features/portfolio/types";
import type { PortfolioRiskAssessment } from "@/features/risk/types";
import { calculatePortfolioRisk } from "@/features/risk/portfolio-risk";
import { getDemoRiskSignals } from "@/features/risk/signals";
import type { MaraAction, MaraAnalysis } from "@/features/mara/types";
import type { OnchainConstitution } from "@/features/constitution/types";
import { createAdaptationPlan } from "./engine";
import { validateAdaptationInput, validateAdaptationPlan } from "./validation";
import { evaluateTargetAllocationCompliance } from "./target-compliance";
import type { AdaptationInput } from "./types";

const vault = getAddress("0x0000000000000000000000000000000000000001");
const owner = getAddress("0x0000000000000000000000000000000000000002");
const assets = createAssetCatalog({ strsy: getAddress("0x0000000000000000000000000000000000000011"), sxau: getAddress("0x0000000000000000000000000000000000000012"), saaplx: getAddress("0x0000000000000000000000000000000000000013") });
const position = (index: number, allocationBps: number, rawBalance = 1n): AssetPosition => ({ asset: assets[index], availability: "available", rawBalance, balanceDecimals: assets[index].expectedDecimals, displayBalance: rawBalance.toString(), referencePrice: { assetId: assets[index].id, value: 100_000_000n, decimals: 8, currency: "USD", source: "fixture", capturedAt: "2026-01-01T00:00:00Z" }, usdValue: rawBalance, usdValueDecimals: 8, allocationBps });
const snapshot = (allocations = [3000, 4000, 2000, 1000]): PortfolioSnapshot => ({ source: "vault", accountAddress: vault, chainId: 1952, blockNumber: 100n, blockConsistency: "single-block", capturedAt: "2026-01-01T00:00:00Z", positions: allocations.map((bps, index) => position(index, bps, bps ? 1n : 0n)), totals: { totalUsdValue: 4n, usdValueDecimals: 8, valuedAssetCount: 4, nonzeroAssetCount: allocations.filter(Boolean).length, unknownBalanceAssetCount: 0 }, valuationStatus: "valued", priceSources: ["fixture"] });
const risk = (snap = snapshot()): PortfolioRiskAssessment => calculatePortfolioRisk(snap, new Map(snap.positions.map((p) => [p.asset.id, getDemoRiskSignals(p.asset.id)])), "2026-01-01T00:00:00Z");
const constitution = (daily = 1000, overrides = {}): OnchainConstitution => ({ version: "phase-6.v1", source: "onchain", vaultAddress: vault, owner, blockNumber: 101n, capturedAt: "2026-01-01T00:00:01Z", constitution: { minimumReserveBps: 2000, maximumSingleAssetExposureBps: 6000, maximumAggressiveExposureBps: 3000, maximumDailyReallocationBps: daily, ...overrides } });
const mara = (proposals: Array<{ action: MaraAction; assetId?: "usdt0" | "strsy" | "sxau" | "saaplx" | null; rationale?: string }> = [{ action: "increase_reserve" }]): MaraAnalysis => ({ status: "complete", summary: "Advisory summary", observations: [], proposals: proposals.map((p) => ({ action: p.action, assetId: p.assetId ?? null, rationale: p.rationale ?? "Grounded direction", evidenceRefs: ["risk.portfolio"], executionAuthority: "none" })), uncertainties: [] });
const input = (changes: Partial<AdaptationInput> = {}): AdaptationInput => { const snap = changes.snapshot ?? snapshot(); return { snapshot: snap, riskAssessment: changes.riskAssessment ?? risk(snap), constitution: changes.constitution ?? constitution(), maraAnalysis: changes.maraAnalysis ?? mara() }; };

describe("deterministic adaptation engine", () => {
  it.each([
    ["wallet source", { snapshot: { ...snapshot(), source: "wallet" } }],
    ["wrong chain", { snapshot: { ...snapshot(), chainId: 1 } }],
    ["partial valuation", { snapshot: { ...snapshot(), valuationStatus: "partial" } }],
    ["unavailable valuation", { snapshot: { ...snapshot(), valuationStatus: "unavailable" } }],
    ["corrupt allocation", { snapshot: snapshot([3000, 4000, 2000, 999]) }],
    ["no meaningful holding", { snapshot: snapshot([0, 0, 0, 0]) }],
  ] as const)("blocks %s", (_label, changes) => expect(createAdaptationPlan(input(changes as Partial<AdaptationInput>)).status).toBe("blocked"));

  it("blocks a wrong vault, incomplete risk, draft policy, invalid policy, infeasible policy, and current violation", () => {
    expect(createAdaptationPlan(input({ constitution: { ...constitution(), vaultAddress: owner } })).status).toBe("blocked");
    expect(createAdaptationPlan(input({ riskAssessment: { ...risk(), status: "partial" } })).status).toBe("blocked");
    expect(createAdaptationPlan(input({ constitution: { version: "phase-6.v1", source: "draft", constitution: constitution().constitution } })).status).toBe("blocked");
    expect(createAdaptationPlan(input({ constitution: { ...constitution(), constitution: { ...constitution().constitution, maximumSingleAssetExposureBps: -1 } } })).status).toBe("blocked");
    expect(createAdaptationPlan(input({ constitution: constitution(500, { maximumSingleAssetExposureBps: 2000 }) })).status).toBe("blocked");
    expect(createAdaptationPlan(input({ constitution: constitution(500, { minimumReserveBps: 4000 }) })).status).toBe("blocked");
  });

  it.each(["maintain", "review"] as const)("maps %s to no action", (action) => { const plan = createAdaptationPlan(input({ maraAnalysis: mara([{ action }]) })); expect(plan.status).toBe("no-action"); expect(plan.reallocationBps).toBe(0); expect(plan.allocations.every((a) => a.deltaBps === 0)).toBe(true); });

  it("uses the highest non-Reserve donor and Reserve destination with a 500-BPS throttle", () => { const plan = createAdaptationPlan(input()); expect(plan.status).toBe("proposed"); expect(plan.reallocationBps).toBe(500); expect(plan.allocations.find((a) => a.assetId === "strsy")?.deltaBps).toBe(-500); expect(plan.allocations.find((a) => a.assetId === "usdt0")?.deltaBps).toBe(500); });
  it.each([[1000, 500], [300, 300], [1, 1]])("caps daily limit %i at %i", (daily, expected) => expect(createAdaptationPlan(input({ constitution: constitution(daily) })).reallocationBps).toBe(expected));
  it("blocks a zero daily limit", () => expect(createAdaptationPlan(input({ constitution: constitution(0) })).blockers).toContain("Active constitution permits no reallocation."));
  it("reduces an explicit donor into Reserve first", () => { const plan = createAdaptationPlan(input({ maraAnalysis: mara([{ action: "reduce_exposure", assetId: "sxau" }]) })); expect(plan.allocations.find((a) => a.assetId === "sxau")?.deltaBps).toBe(-500); expect(plan.allocations.find((a) => a.assetId === "usdt0")?.deltaBps).toBe(500); });
  it("returns no-action for a nonmeaningful referenced donor", () => { const snap = snapshot([3000, 5000, 2000, 0]); expect(createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap), maraAnalysis: mara([{ action: "reduce_exposure", assetId: "saaplx" }]) })).status).toBe("no-action"); });
  it("fails closed instead of inventing donors for null-target exposure actions", () => { for (const action of ["diversify", "reduce_exposure"] as const) { const plan = createAdaptationPlan(input({ maraAnalysis: mara([{ action, assetId: null }]) })); expect(plan.status).toBe("no-action"); expect(plan.reallocationBps).toBe(0); expect(plan.allocations.every((item) => item.deltaBps === 0)).toBe(true); } });
  it("produces the canonical targeted diversify plan with a non-Aggressive receiver", () => { const snap = snapshot([4000, 3000, 2000, 1000]); const plan = createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap), maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) })); expect(plan.status).toBe("proposed"); expect(plan.executionAuthority).toBe("none"); expect(plan.reallocationBps).toBe(500); expect(plan.allocations.map((item) => item.targetAllocationBps)).toEqual([4000, 3500, 1500, 1000]); expect(plan.postPlanCompliance?.status).toBe("compliant"); });
  it("prefers a non-Aggressive receiver over a lower-allocation Aggressive receiver", () => { const snap = snapshot([4000, 3000, 2000, 1000]); const plan = createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap), maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) })); expect(plan.allocations.find((a) => a.assetId === "strsy")?.deltaBps).toBe(500); expect(plan.allocations.find((a) => a.assetId === "saaplx")?.deltaBps).toBe(0); });
  it("uses an Aggressive receiver only when non-Aggressive destinations have no capacity", () => { const snap = snapshot([3000, 3000, 3000, 1000]); const policy = constitution(1000, { maximumSingleAssetExposureBps: 3000 }); const plan = createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap), constitution: policy, maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) })); expect(plan.status).toBe("proposed"); expect(plan.allocations.find((a) => a.assetId === "saaplx")?.deltaBps).toBe(500); expect(plan.postPlanCompliance?.status).toBe("compliant"); });
  it("uses canonical order to break equal-allocation destination ties", () => { const snap = snapshot([3000, 3000, 2000, 2000]); const plan = createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap), maraAnalysis: mara([{ action: "diversify", assetId: "strsy" }]) })); expect(plan.allocations.find((a) => a.assetId === "sxau")?.deltaBps).toBe(500); });
  it("selects only the first actionable proposal after non-allocation ideas", () => { const plan = createAdaptationPlan(input({ maraAnalysis: mara([{ action: "review" }, { action: "reduce_exposure", assetId: "sxau" }, { action: "increase_reserve" }]) })); expect(plan.selectedProposalIndex).toBe(1); expect(plan.selectedAction).toBe("reduce_exposure"); expect(plan.allocations.filter((a) => a.deltaBps !== 0)).toHaveLength(2); });
  it("does not derive allocation math from MARA prose numbers", () => { const a = createAdaptationPlan(input({ maraAnalysis: mara([{ action: "reduce_exposure", assetId: "sxau", rationale: "Move 17.5%" }]) })); const b = createAdaptationPlan(input({ maraAnalysis: mara([{ action: "reduce_exposure", assetId: "sxau", rationale: "Move 99 bps" }]) })); expect(a.allocations).toEqual(b.allocations); });
  it("uses baseline rather than dynamic risk tier for aggressive limits", () => { const snap = snapshot(); const assessed = calculatePortfolioRisk(snap, new Map(snap.positions.map((p) => [p.asset.id, p.asset.id === "strsy" ? { assetId: "strsy", source: "fixture", volatilityScoreBps: 10_000, liquidityScoreBps: 10_000, referenceDeviationScoreBps: 10_000, issuerCollateralScoreBps: 10_000, marketEventStressScoreBps: 10_000 } : getDemoRiskSignals(p.asset.id)])), "2026-01-01T00:00:00Z"); expect(assessed.assetAssessments.find((a) => a.assetId === "strsy")?.currentRiskTier).toBe("Aggressive"); const plan = createAdaptationPlan(input({ snapshot: snap, riskAssessment: assessed, maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) })); expect(plan.status).toBe("proposed"); });
  it("caps movement by receiver headroom and reserve/aggressive policy", () => { const headroomSnapshot = snapshot([3000, 3000, 2500, 1500]); const headroom = createAdaptationPlan(input({ snapshot: headroomSnapshot, riskAssessment: risk(headroomSnapshot), constitution: constitution(1000, { maximumSingleAssetExposureBps: 3200 }), maraAnalysis: mara([{ action: "increase_reserve" }]) })); expect(headroom.reallocationBps).toBe(200); const snap = snapshot([3000, 3000, 3000, 1000]); const aggressive = createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap), constitution: constitution(1000, { maximumSingleAssetExposureBps: 3000, maximumAggressiveExposureBps: 1100 }), maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) })); expect(aggressive.reallocationBps).toBe(100); });
  it("independently validates exact-BPS plan invariants", () => { const value = input(); const plan = createAdaptationPlan(value); expect(validateAdaptationPlan(plan, value)).toEqual([]); expect(plan.allocations.reduce((sum, a) => sum + a.targetAllocationBps, 0)).toBe(10_000); expect(plan.allocations.reduce((sum, a) => sum + Math.max(0, a.deltaBps), 0)).toBe(plan.reallocationBps); });
  it("keeps deterministic invariants over a table of daily limits", () => { for (let daily = 1; daily <= 1000; daily += 37) { const value = input({ constitution: constitution(daily) }); const plan = createAdaptationPlan(value); expect(plan.status).toBe("proposed"); expect(validateAdaptationPlan(plan, value)).toEqual([]); expect(plan.reallocationBps).toBeLessThanOrEqual(Math.min(500, daily)); } });

  it.each([[100, [4000, 100, 3900, 2000]], [1, [4000, 1, 3999, 2000]]] as const)("caps movement by a %i-BPS donor", (expected, allocations) => { const snap = snapshot([...allocations]); const value = input({ snapshot: snap, riskAssessment: risk(snap), maraAnalysis: mara([{ action: "reduce_exposure", assetId: "strsy" }]) }); const plan = createAdaptationPlan(value); expect(plan.status).toBe("proposed"); expect(plan.reallocationBps).toBe(expected); expect(plan.allocations.find((a) => a.assetId === "strsy")?.targetAllocationBps).toBe(0); });

  it("allocates to a configured known-zero receiver without fabricating a balance", () => { const snap = snapshot([3500, 3500, 3000, 0]); const value = input({ snapshot: snap, riskAssessment: risk(snap), constitution: constitution(1000, { maximumSingleAssetExposureBps: 3500 }), maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) }); const plan = createAdaptationPlan(value); expect(plan.status).toBe("proposed"); expect(plan.allocations.find((a) => a.assetId === "saaplx")?.targetAllocationBps).toBe(500); expect(snap.positions.find((p) => p.asset.id === "saaplx")?.rawBalance).toBe(0n); expect(plan.postPlanCompliance?.status).toBe("compliant"); expect(validateAdaptationPlan(plan, value)).toEqual([]); });

  it("rejects adversarial plan asset maps and authoritative-current mutations", () => { const value = input(); const valid = createAdaptationPlan(value); const duplicate = { ...valid, allocations: valid.allocations.map((a, i) => i === 1 ? { ...a, assetId: valid.allocations[0].assetId } : a) }; expect(validateAdaptationPlan(duplicate, value)).not.toEqual([]); const unknown = { ...valid, allocations: valid.allocations.map((a, i) => i === 0 ? { ...a, assetId: "unknown" as never } : a) }; expect(validateAdaptationPlan(unknown, value)).not.toEqual([]); const changed = { ...valid, allocations: valid.allocations.map((a, i) => i === 0 ? { ...a, currentAllocationBps: a.currentAllocationBps + 1 } : a) }; expect(validateAdaptationPlan(changed, value)).not.toEqual([]); const negative = { ...valid, allocations: valid.allocations.map((a, i) => i === 0 ? { ...a, currentAllocationBps: -1 } : a) }; expect(validateAdaptationPlan(negative, value)).not.toEqual([]); });

  it("rejects forged safety fields independently", () => { const value = input({ constitution: constitution(300) }); const valid = createAdaptationPlan(value); expect(validateAdaptationPlan({ ...valid, stepBudgetBps: 500 }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, constitutionReallocationLimitBps: 500 }, value)).not.toEqual([]); const allocations = valid.allocations.map((a) => ({ ...a, deltaBps: a.deltaBps < 0 ? -500 : a.deltaBps > 0 ? 500 : 0, targetAllocationBps: a.currentAllocationBps + (a.deltaBps < 0 ? -500 : a.deltaBps > 0 ? 500 : 0) })); const forged = { ...valid, reallocationBps: 500, allocations, postPlanCompliance: evaluateTargetAllocationCompliance(allocations, assets, constitution(300).constitution) }; expect(validateAdaptationPlan(forged, value)).not.toEqual([]); });

  it("rejects forged MARA provenance", () => { const value = input(); const valid = createAdaptationPlan(value); expect(validateAdaptationPlan({ ...valid, selectedProposalIndex: 2 }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, selectedAction: "diversify" }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, selectedAssetId: "sxau" }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, maraEvidenceRefs: ["forged"] }, value)).not.toEqual([]); });
  it("rejects a compliant pair that does not match deterministic action semantics", () => { const snap = snapshot([4000, 3000, 2000, 1000]); const value = input({ snapshot: snap, riskAssessment: risk(snap), maraAnalysis: mara([{ action: "diversify", assetId: "sxau" }]) }); const valid = createAdaptationPlan(value); const allocations = valid.allocations.map((item) => item.assetId === "strsy" ? { ...item, targetAllocationBps: item.currentAllocationBps, deltaBps: 0 } : item.assetId === "usdt0" ? { ...item, targetAllocationBps: item.currentAllocationBps + 500, deltaBps: 500 } : item); const forged = { ...valid, allocations, postPlanCompliance: evaluateTargetAllocationCompliance(allocations, assets, constitution().constitution) }; expect(forged.postPlanCompliance.status).toBe("compliant"); expect(validateAdaptationPlan(forged, value)).toContain("Plan movement does not match the deterministic action, donor, receiver, or capacity policy."); });

  it("rejects a target policy violation even with forged recorded compliance", () => { const value = input(); const valid = createAdaptationPlan(value); const allocations = valid.allocations.map((a) => a.assetId === "usdt0" ? { ...a, targetAllocationBps: 6500, deltaBps: 3500 } : a.assetId === "strsy" ? { ...a, targetAllocationBps: 500, deltaBps: -3500 } : a); const forged = { ...valid, reallocationBps: 3500, allocations }; expect(validateAdaptationPlan(forged, value)).not.toEqual([]); });

  it("blocks forged canonical metadata and incoherent assessed risk", () => { const forgedSnapshot = snapshot(); forgedSnapshot.positions[1].asset = { ...forgedSnapshot.positions[1].asset, baselineRiskTier: "Aggressive" }; expect(createAdaptationPlan(input({ snapshot: forgedSnapshot, riskAssessment: risk(forgedSnapshot) })).status).toBe("blocked"); const snap = snapshot(); const assessed = risk(snap); assessed.assetAssessments[0].factors[0].weightBps = 1; expect(createAdaptationPlan(input({ snapshot: snap, riskAssessment: assessed })).status).toBe("blocked"); });

  it.each([
    ["symbol", { symbol: "FORGED" }],
    ["display name", { displayName: "Forged display name" }],
    ["role", { role: "forged-role" }],
    ["baseline risk tier", { baselineRiskTier: "Aggressive" as const }],
    ["expected decimals", { expectedDecimals: 6 }],
    ["sandbox flag", { sandbox: false }],
    ["reference price ID", { referencePriceId: "forged-price" }],
  ])("blocks forged canonical %s metadata", (_label, forged) => { const snap = snapshot(); snap.positions[1].asset = { ...snap.positions[1].asset, ...forged }; expect(createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap) })).status).toBe("blocked"); });

  it("blocks a mixed-block snapshot", () => { const snap = { ...snapshot(), blockConsistency: "latest-near-simultaneous" as const }; expect(createAdaptationPlan(input({ snapshot: snap, riskAssessment: risk(snap) })).status).toBe("blocked"); });

  it("requires every canonical asset even when the omitted position is known zero", () => { const snap = snapshot([3000, 4000, 3000, 0]); snap.positions = snap.positions.slice(0, 3); const value = input({ snapshot: snap, riskAssessment: risk(snap) }); expect(validateAdaptationInput(value)).toContain("The portfolio must contain every canonical Adaptara asset exactly once."); expect(createAdaptationPlan(value).status).toBe("blocked"); });

  it.each([
    ["read-error disguised as zero", { availability: "read-error" as const, rawBalance: 0n }],
    ["configuration-error disguised as zero", { availability: "configuration-error" as const, rawBalance: 0n }],
    ["available unknown balance", { availability: "available" as const, rawBalance: null }],
    ["available wrong decimals", { availability: "available" as const, balanceDecimals: 6 }],
  ])("blocks incoherent availability state: %s", (_label, hostile) => { const snap = snapshot([3000, 4000, 3000, 0]); snap.positions[3] = { ...snap.positions[3], ...hostile }; const value = input({ snapshot: snap, riskAssessment: risk(snap) }); expect(validateAdaptationInput(value).some((error) => /known balance|unknown balance|canonical decimals/.test(error))).toBe(true); expect(createAdaptationPlan(value).status).toBe("blocked"); });

  it("rejects independently forged plan provenance fields", () => { const value = input(); const valid = createAdaptationPlan(value); expect(validateAdaptationPlan(valid, value)).toEqual([]); expect(validateAdaptationPlan({ ...valid, vaultAddress: owner }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, chainId: 1 }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, portfolioBlockNumber: 999n }, value)).not.toEqual([]); expect(validateAdaptationPlan({ ...valid, constitutionBlockNumber: 999n }, value)).not.toEqual([]); });

  it("rejects a valid-looking plan when authoritative risk becomes incoherent", () => { const validInput = input(); const valid = createAdaptationPlan(validInput); const incoherent = risk(validInput.snapshot); incoherent.assetAssessments[0].factors[0].weightedContributionBps += 1; expect(validateAdaptationPlan(valid, { ...validInput, riskAssessment: incoherent })).not.toEqual([]); });

  it("rejects a valid-looking plan against wrong-vault authoritative input", () => { const validInput = input(); const valid = createAdaptationPlan(validInput); expect(validateAdaptationPlan(valid, { ...validInput, constitution: { ...constitution(), vaultAddress: owner } })).not.toEqual([]); });
});
