import { describe, expect, it } from "vitest";
import { createSentinelAssessment, stressBpsForSeverity } from "./assessment";
import type { SentinelObservation } from "./types";

const asOf = "2026-01-10T12:00:00.000Z";
const report = (overrides: Partial<SentinelObservation> = {}): SentinelObservation => ({ observationId: "o1", eventKey: "event-a", sourceId: "source-a", sourceLabel: "Fixture Source A", publishedAt: "2026-01-10T11:00:00.000Z", headline: "Synthetic fixture event", summary: "Original fixture text for deterministic tests.", affectedAssetIds: ["strsy"], eventType: "liquidity_market", severity: "medium", ...overrides });
const assess = (observations: SentinelObservation[], assets = ["strsy"] as const) => createSentinelAssessment(assets, observations, asOf);

describe("Sentinel deterministic assessment", () => {
  it.each([["low", 2500], ["medium", 5000], ["high", 7500], ["critical", 10000]] as const)("maps %s severity to %i BPS", (severity, bps) => expect(stressBpsForSeverity(severity)).toBe(bps));
  it("corroborates the same event and asset from two distinct sources", () => expect(assess([report(), report({ observationId: "o2", sourceId: "source-b" })]).assetStress[0].sentinelEventStressBps).toBe(5000));
  it("does not count a duplicate report from the same source", () => expect(assess([report(), report({ observationId: "o2" })]).assetStress[0].sentinelEventStressBps).toBe(0));
  it("does not combine unrelated event keys", () => expect(assess([report(), report({ observationId: "o2", eventKey: "event-b", sourceId: "source-b" })]).eventGroups).toHaveLength(2));
  it("keeps a single-source critical event informational", () => expect(assess([report({ severity: "critical" })]).assetStress[0].sentinelEventStressBps).toBe(0));
  it("treats 71h59m as active", () => { const publishedAt = new Date(Date.parse(asOf) - (71 * 60 + 59) * 60_000).toISOString(); expect(assess([report({ publishedAt }), report({ observationId: "o2", sourceId: "source-b", publishedAt })]).assetStress[0].sentinelEventStressBps).toBe(5000); });
  it("treats the exact 72-hour boundary as expired", () => { const publishedAt = new Date(Date.parse(asOf) - 72 * 3_600_000).toISOString(); expect(assess([report({ publishedAt, severity: "critical" }), report({ observationId: "o2", sourceId: "source-b", publishedAt, severity: "critical" })]).assetStress[0].sentinelEventStressBps).toBe(0); });
  it("does not let one expired critical source corroborate one active low source", () => { const expired = new Date(Date.parse(asOf) - 80 * 3_600_000).toISOString(); const result = assess([report({ publishedAt: expired, severity: "critical" }), report({ observationId: "o2", sourceId: "source-b", severity: "low" })]); expect(result.eventGroups[0].assetStatuses[0]).toMatchObject({ activeSourceCount: 1, activeSeverity: null, status: "uncorroborated" }); expect(result.assetStress[0].sentinelEventStressBps).toBe(0); });
  it("uses the highest severity among two active relevant sources", () => { const result = assess([report({ severity: "critical" }), report({ observationId: "o2", sourceId: "source-b", severity: "low" })]); expect(result.eventGroups[0].assetStatuses[0]).toMatchObject({ activeSourceCount: 2, activeSeverity: "critical", status: "corroborated-active" }); expect(result.assetStress[0].sentinelEventStressBps).toBe(10_000); });
  it("labels two distinct expired sources corroborated-expired with zero stress", () => { const result = assess([report({ publishedAt: new Date(Date.parse(asOf) - 80 * 3_600_000).toISOString() }), report({ observationId: "o2", sourceId: "source-b", publishedAt: new Date(Date.parse(asOf) - 79 * 3_600_000).toISOString() })]); expect(result.eventGroups[0].assetStatuses[0].status).toBe("corroborated-expired"); expect(result.assetStress[0].sentinelEventStressBps).toBe(0); });
  it("rejects observations beyond five minutes in the future", () => expect(() => assess([report({ publishedAt: new Date(Date.parse(asOf) + 300_001).toISOString() })])).toThrow(/future-dated/));
  it("uses max rather than sum across active events", () => { const observations = [report(), report({ observationId: "o2", sourceId: "source-b" }), report({ observationId: "o3", eventKey: "event-b", sourceId: "source-c", severity: "high" }), report({ observationId: "o4", eventKey: "event-b", sourceId: "source-d", severity: "high" })]; expect(assess(observations).assetStress[0].sentinelEventStressBps).toBe(7500); });
  it("applies a multi-asset event only to affected requested assets", () => { const observations = [report({ affectedAssetIds: ["strsy", "sxau"] }), report({ observationId: "o2", sourceId: "source-b", affectedAssetIds: ["strsy", "sxau"] })]; const result = createSentinelAssessment(["strsy", "sxau", "saaplx"], observations, asOf); expect(result.assetStress.map((item) => item.sentinelEventStressBps)).toEqual([5000, 5000, 0]); });
  it("does not cross-corroborate reports for different assets sharing an event key", () => { const result = createSentinelAssessment(["strsy", "sxau"], [report({ affectedAssetIds: ["strsy"] }), report({ observationId: "o2", sourceId: "source-b", affectedAssetIds: ["sxau"] })], asOf); expect(result.assetStress.map((item) => item.sentinelEventStressBps)).toEqual([0, 0]); expect(result.eventGroups[0].assetStatuses.map((item) => item.activeSourceCount)).toEqual([1, 1]); });
  it("derives active source count and severity independently for each asset in a mixed event", () => { const observations = [report({ sourceId: "a", severity: "critical", affectedAssetIds: ["strsy"] }), report({ observationId: "o2", sourceId: "b", severity: "low", affectedAssetIds: ["strsy"] }), report({ observationId: "o3", sourceId: "c", severity: "medium", affectedAssetIds: ["sxau"] }), report({ observationId: "o4", sourceId: "d", severity: "low", affectedAssetIds: ["sxau"] }), report({ observationId: "o5", sourceId: "e", severity: "critical", affectedAssetIds: ["sxau"], publishedAt: new Date(Date.parse(asOf) - 80 * 3_600_000).toISOString() })]; const result = createSentinelAssessment(["strsy", "sxau"], observations, asOf); expect(result.eventGroups[0].assetStatuses).toEqual([{ assetId: "strsy", sourceCount: 2, activeSourceCount: 2, activeSeverity: "critical", status: "corroborated-active" }, { assetId: "sxau", sourceCount: 3, activeSourceCount: 2, activeSeverity: "medium", status: "corroborated-active" }]); expect(result.assetStress.map((item) => item.sentinelEventStressBps)).toEqual([10_000, 5_000]); });
  it("rejects duplicate observation IDs", () => expect(() => assess([report(), report({ sourceId: "source-b" })])).toThrow(/unique/));
  it("rejects conflicting event types under one event key", () => expect(() => assess([report(), report({ observationId: "o2", sourceId: "source-b", eventType: "operational_cyber" })])).toThrow(/conflicting event types/));
  it("accepts consistent event types under one event key", () => expect(assess([report(), report({ observationId: "o2", sourceId: "source-b" })]).eventGroups[0].eventType).toBe("liquidity_market"));
  it("rejects unknown assets and arbitrary numeric provider risk", () => { const malformed = { ...report(), affectedAssetIds: ["unknown"], riskBps: 9000 }; expect(() => createSentinelAssessment(["strsy"], [malformed], asOf)).toThrow(); });
  it("returns truthful demo authority and limitations", () => expect(assess([])).toMatchObject({ version: "phase-8.v1", status: "complete", executionAuthority: "none", feedMode: "demo" }));
});
