import { describe, expect, it } from "vitest";
import { getDemoRiskSignals } from "@/features/risk/signals";
import { calculatePortfolioRisk } from "@/features/risk/portfolio-risk";
import { createAssetCatalog } from "@/features/portfolio/catalog";
import type { PortfolioSnapshot } from "@/features/portfolio/types";
import { maraAnalysisForContext, maraContextFingerprint } from "@/features/mara/context";
import { adaptationContextKey } from "@/features/adaptation/components/adaptation-plan";
import type { MaraAnalysis } from "@/features/mara/types";
import { overlaySentinelStress, riskAssessedAtWithSentinel, sentinelInfluencesPortfolioRisk } from "./effective-signals";
import type { SentinelAssessment } from "./types";

const assessment = (bps: number): SentinelAssessment => ({ version: "phase-8.v1", status: "complete", executionAuthority: "none", feedMode: "demo", asOf: "2026-01-01T00:00:00.000Z", requestedAssetIds: ["strsy"], observations: [], eventGroups: [], assetStress: [{ assetId: "strsy", sentinelEventStressBps: bps, activeCorroboratedEventKeys: [] }], limitations: [] });
const asset = createAssetCatalog()[1];
const snapshot = (rawBalance: bigint | null = 1n): PortfolioSnapshot => ({ source: "vault", accountAddress: "0x0000000000000000000000000000000000000001", chainId: 1952, blockNumber: 10n, blockConsistency: "single-block", capturedAt: "2025-12-31T00:00:00.000Z", positions: [{ asset, availability: "available", rawBalance, balanceDecimals: 18, displayBalance: rawBalance === null ? null : "1", referencePrice: null, usdValue: rawBalance === null ? null : 1n, usdValueDecimals: 2, allocationBps: 10_000 }], totals: { totalUsdValue: 1n, usdValueDecimals: 2, valuedAssetCount: 1, nonzeroAssetCount: rawBalance && rawBalance > 0n ? 1 : 0, unknownBalanceAssetCount: rawBalance === null ? 1 : 0 }, valuationStatus: "valued", priceSources: ["demo"] });
const base = () => new Map([["strsy", getDemoRiskSignals("strsy")]]);
describe("Sentinel signal overlay", () => {
  it("raises base event stress when Sentinel is higher", () => expect(overlaySentinelStress(new Map([["strsy", getDemoRiskSignals("strsy")]]), assessment(7500)).get("strsy")?.marketEventStressScoreBps).toBe(7500));
  it("never lowers base event stress", () => { const base = { ...getDemoRiskSignals("strsy")!, marketEventStressScoreBps: 8000 }; expect(overlaySentinelStress(new Map([["strsy", base]]), assessment(5000)).get("strsy")?.marketEventStressScoreBps).toBe(8000); });
  it("leaves base unchanged for zero stress", () => expect(overlaySentinelStress(new Map([["strsy", getDemoRiskSignals("strsy")]]), assessment(0)).get("strsy")).toEqual(getDemoRiskSignals("strsy")));
  it("influences risk only for a meaningful holding with an available lower base signal", () => { expect(sentinelInfluencesPortfolioRisk(snapshot(), base(), assessment(7500))).toBe(true); expect(sentinelInfluencesPortfolioRisk(snapshot(0n), base(), assessment(7500))).toBe(false); expect(sentinelInfluencesPortfolioRisk(snapshot(null), base(), assessment(7500))).toBe(false); expect(sentinelInfluencesPortfolioRisk(snapshot(), new Map(), assessment(7500))).toBe(false); expect(sentinelInfluencesPortfolioRisk(snapshot(), base(), assessment(1000))).toBe(false); });
  it("preserves risk, MARA, and adaptation identities for a no-op scan", () => { const snap = snapshot(); const baseSignals = base(); const before = calculatePortfolioRisk(snap, baseSignals, snap.capturedAt); const noOp = assessment(1000); const after = calculatePortfolioRisk(snap, overlaySentinelStress(baseSignals, noOp), riskAssessedAtWithSentinel(snap, baseSignals, noOp)); const beforeKey = maraContextFingerprint(snap, before); const afterKey = maraContextFingerprint(snap, after); const analysis = { status: "complete", proposals: [] } as unknown as MaraAnalysis; expect(after).toEqual(before); expect(after.assessedAt).toBe(snap.capturedAt); expect(afterKey).toBe(beforeKey); expect(maraAnalysisForContext({ contextKey: beforeKey, analysis }, afterKey)).toBe(analysis); expect(adaptationContextKey(snap, after, undefined, analysis)).toBe(adaptationContextKey(snap, before, undefined, analysis)); });
  it("changes risk, MARA, and adaptation identities when Sentinel raises meaningful stress", () => { const snap = snapshot(); const baseSignals = base(); const before = calculatePortfolioRisk(snap, baseSignals, snap.capturedAt); const raised = assessment(7500); const after = calculatePortfolioRisk(snap, overlaySentinelStress(baseSignals, raised), riskAssessedAtWithSentinel(snap, baseSignals, raised)); const beforeKey = maraContextFingerprint(snap, before); const afterKey = maraContextFingerprint(snap, after); const analysis = { status: "complete", proposals: [] } as unknown as MaraAnalysis; expect(after.assessedAt).toBe(raised.asOf); expect(after).not.toEqual(before); expect(afterKey).not.toBe(beforeKey); expect(maraAnalysisForContext({ contextKey: beforeKey, analysis }, afterKey)).toBeNull(); expect(adaptationContextKey(snap, after, undefined, analysis)).not.toBe(adaptationContextKey(snap, before, undefined, analysis)); });
});
