[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

[invariant]
runs = 128
depth = 64
fail_on_revert = false

[rpc_endpoints]
xlayer_mainnet = "${XLAYER_MAINNET_RPC_URL}"
xlayer_testnet = "${XLAYER_TESTNET_RPC_URL}"
