import Link from "next/link";
import type { ReactNode } from "react";
import { ApplicationHeader } from "./application-header";
import { MingcuteIcon } from "@/components/ui/mingcute-icon";
import { DEMO_ACTIVITY, DEMO_VAULTS } from "../demo-fixtures";

export const DEMO_VIEWS = ["Home", "Portfolio", "Vaults", "Activity"] as const;
type DemoView = (typeof DEMO_VIEWS)[number];
const metrics = [["Total Portfolio","$25,000","Current total position"],["In Vaults","$10,500","42% of portfolio"],["Outside Vaults","$14,500","Wallet control"],["Active Vaults","3","3 Constitutions"]] as const;
const holdings = [["xETH","5.42 xETH","$10,500","42%","Balanced","Wallet + 2 Vaults"],["USDT","8,500 USDT","$8,500","34%","Reserve","Wallet + 2 Vaults"],["Other","—","$6,000","24%","Mixed","Wallet + Vaults"]] as const;
function MetricRow({items=metrics}:{items?:readonly (readonly [string,string,string])[]}) { return <section className="final-metrics">{items.map(([label,value,note])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>)}</section> }
function PageHead({title,copy,aside}:{title:string;copy:string;aside?:ReactNode}) { return <header className="final-page-head"><div><h1>{title}</h1><p>{copy}</p></div>{aside}</header> }
function Allocation() { return <article className="final-section final-allocation"><header><span>Allocation</span></header><div className="final-donut" aria-label="Outside Vault 58%, Growth Vault 22%, Reserve Vault 12%, Opportunity Vault 8%"><i/></div><dl>{[["Outside Vault","58%"],["Growth Vault","22%"],["Reserve Vault","12%"],["Opportunity Vault","8%"]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></article> }
function MaraPanel() { return <section className="final-section final-mara"><header><div><span>MARA Intelligence</span><p>MARA sees one item worth reviewing: Growth Vault concentration is near its policy threshold.</p></div><Link href="/demo?view=portfolio">Ask MARA <MingcuteIcon name="arrowRight" size={16} /></Link></header><div>{[["What changed","xETH exposure increased to 47%"],["Why it matters","Growth Vault permits a maximum concentration of 50%"],["Recommended next step","Review Growth Vault allocation"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</div><footer><strong>BLOCKED</strong><span>Projected concentration 63% · Nothing moved · No transaction submitted</span></footer></section> }
function VaultCards() { return <section className="final-section final-vault-preview"><h2>Your Vaults</h2><div>{DEMO_VAULTS.map(v=><article key={v.name}><small>{v.name}</small><strong>{v.balance}</strong><span>{v.mode} · <em data-health={v.health}>{v.health}</em></span></article>)}</div></section> }
function DemoHome(){return <><PageHead title="Overview" copy="Simulated X Layer portfolio, Vaults and current Adaptara position."/><MetricRow/><section className="final-triptych"><Allocation/><article className="final-section final-state"><header><span>Portfolio state</span><em>Balanced</em></header><dl><div><dt>Reserve</dt><dd>34%</dd></div><div><dt>Balanced</dt><dd>46%</dd></div><div><dt>Aggressive</dt><dd>20%</dd></div></dl><p>No current limit violations</p></article><article className="final-section final-health"><header><span>Vault health</span></header><dl>{DEMO_VAULTS.map(v=><div key={v.name}><dt>{v.name}</dt><dd data-health={v.health}>{v.health}</dd></div>)}</dl><p>1 Advisory · 2 Approval Required</p></article></section><MaraPanel/><VaultCards/><section className="final-section final-table"><h2>Recent Activity</h2>{[["MARA flagged Growth Vault concentration","MARA · Attention","10 mins ago"],["Reserve Vault policy reviewed","Policy · Completed","2h ago"],["Opportunity Vault valuation refreshed","Derived · Completed","5h ago"],["Wallet connected on X Layer","Simulation","Today"]].map(row=><div key={row[0]}>{row.map(v=><span key={v}>{v}</span>)}</div>)}</section></>}
function DemoPortfolio(){const m=[["Total Portfolio","$25,000","Simulated total"],["Wallet Holdings","$14,500","Outside Adaptara"],["Managed in Vaults","$10,500","Intentionally delegated"],["Portfolio State","Balanced","Within thresholds"]] as const;return <><PageHead title="Portfolio" copy="Your complete X Layer position, across wallet-held and Adaptara-managed assets."/><MetricRow items={m}/><section className="final-section final-wide-allocation"><h2>Asset Allocation</h2><div className="final-stack"><i/><i/><i/></div>{[["xETH","42%","$10,500"],["USDT","34%","$8,500"],["Other","24%","$6,000"]].map(r=><div key={r[0]}>{r.map(v=><span key={v}>{v}</span>)}</div>)}</section><section className="final-two"><article className="final-section"><h2>Risk Exposure</h2><dl className="final-list"><div><dt>Reserve</dt><dd>34%</dd></div><div><dt>Balanced</dt><dd>46%</dd></div><div><dt>Aggressive</dt><dd>20%</dd></div></dl><p>Portfolio state: Balanced. Exposure remains within current risk thresholds.</p></article><article className="final-section"><h2>Custody Split</h2><dl className="final-list"><div><dt>Outside Adaptara</dt><dd>$14,500</dd></div><div><dt>Managed by Adaptara</dt><dd>$10,500</dd></div></dl><p>Only intentionally delegated capital enters Adaptara&apos;s management boundary.</p></article></section><section className="final-section final-holdings"><h2>Holdings</h2><div className="final-table-head">{["Asset","Balance","Value","Allocation","Risk","Location"].map(v=><span key={v}>{v}</span>)}</div>{holdings.map(row=><div key={row[0]}>{row.map(v=><span key={v}>{v}</span>)}</div>)}</section><MaraPanel/><section className="final-section final-location"><h2>Where capital is managed</h2>{[["Outside Adaptara","$14,500","58%"],["Growth Vault","$4,800","19.2%"],["Reserve Vault","$3,900","15.6%"],["Opportunity Vault","$1,800","7.2%"]].map(r=><div key={r[0]}><span>{r[0]}</span><i style={{width:r[2]}}/><strong>{r[1]} · {r[2]}</strong></div>)}</section></>}
function DemoVaults(){const m=[["Managed Capital","$10,500","42% of portfolio"],["Active Vaults","3","3 Constitutions"],["Needs Attention","1","Growth Vault"],["Management Modes","2 / 1","Approval Required / Advisory"]] as const;return <><PageHead title="Vaults" copy="Delegate selected capital into independently governed portfolios." aside={<div className="final-head-action"><span>3 / 16 Vaults</span><button disabled title="Creation remains disabled during controlled rollout">Create Vault</button></div>}/><MetricRow items={m}/><section className="final-vault-list">{DEMO_VAULTS.map((v,i)=><article className="final-section" key={v.name}><header><div><small>{v.name}</small><strong>{v.balance}</strong></div><div><span>{v.mode}</span><em data-health={v.health}>{v.health}</em></div></header><dl>{(i===0?[["Minimum reserve","20%"],["Maximum asset","50%"],["Maximum aggressive","30%"],["Daily turnover","10%"]]:i===1?[["Minimum reserve","60%"],["Maximum asset","20%"],["Maximum aggressive","10%"],["Daily turnover","5%"]]:[["Minimum reserve","25%"],["Maximum asset","45%"],["Maximum aggressive","35%"],["Daily turnover","8%"]]).map(r=><div key={r[0]}><dt>{r[0]}</dt><dd>{r[1]}</dd></div>)}</dl><p>MARA: {v.mara}</p></article>)}</section><section className="final-two"><article className="final-section final-list"><h2>Managed Capital Distribution</h2>{[["Growth","$4,800 · 45.7%"],["Reserve","$3,900 · 37.1%"],["Opportunity","$1,800 · 17.2%"]].map(r=><div key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong></div>)}</article><article className="final-section"><h2>Constitutions Overview</h2><p>Every Vault above has independent reserve, exposure, aggression and turnover rules. No global Constitution controls all Vaults.</p></article></section></>}
function DemoActivity(){const m=[["Total Events","24","Simulation records"],["Vault Actions","8","Across 3 Vaults"],["MARA Signals","11","Advisory only"],["Policy Blocks","2","Nothing moved"]] as const;return <><PageHead title="Activity" copy="Track portfolio events, Vault actions, MARA observations and policy decisions." aside={<div className="final-filters"><span>All activity</span><span>All Vaults</span></div>}/><MetricRow items={m}/><section className="final-section final-activity"><div className="final-table-head">{["Time","Event","Vault","Source","Result"].map(v=><span key={v}>{v}</span>)}</div>{[["10:42 AM","MARA flagged xETH concentration","Growth Vault","Simulation · MARA","Attention"],["10:39 AM","Rebalance proposal blocked","Growth Vault","Simulation · Constitution","Blocked · Nothing moved"],["09:18 AM","Portfolio valuation refreshed","—","Simulation · Derived","Completed"],["Yesterday","Reserve Vault policy reviewed","Reserve Vault","Simulation · Policy","Completed"]].map(row=><div key={row[1]}>{row.map(v=><span key={v}>{v}</span>)}</div>)}</section><aside className="final-section final-detail"><small>Selected activity · Simulation provenance</small><h2>Rebalance proposal blocked</h2><p>Growth Vault · xETH concentration is rising.</p><dl><div><dt>Current</dt><dd>47%</dd></div><div><dt>Maximum</dt><dd>50%</dd></div><div><dt>Projected result</dt><dd>63%</dd></div><div><dt>Outcome</dt><dd>BLOCKED</dd></div></dl><strong>Nothing moved.</strong><span>No transaction was submitted.</span></aside><span className="sr-only">{DEMO_ACTIVITY.length} simulation provenance records</span></>}
export function DemoDashboard({view="Home"}:{view?:DemoView}){return <main className="final-app demo-product"><ApplicationHeader navigation={DEMO_VIEWS.map(item=><Link key={item} href={item==="Home"?"/demo":`/demo?view=${item.toLowerCase()}`} aria-current={view===item?"page":undefined}>{item}</Link>)} context={<><span className="final-demo-badge">Demo Mode<small>Simulated environment · No real funds</small></span><Link className="final-switch-live" href="/dashboard">Switch to Live</Link></>}/><div className="final-app-canvas">{view==="Home"?<DemoHome/>:view==="Portfolio"?<DemoPortfolio/>:view==="Vaults"?<DemoVaults/>:<DemoActivity/>}</div></main>}
