export function PortfolioIntelligencePreview() {
  return <div className="lp-product-story lp-portfolio-story" role="img" aria-label="Portfolio Intelligence preview showing allocation, risk, and the custody boundary"><header><span>Portfolio</span><small>Read-only view</small></header><section className="lp-story-metric"><small>Total portfolio</small><strong>$25,000</strong><em>Balanced</em></section><section><div className="lp-story-heading"><span>Asset allocation</span><small>Visible holdings</small></div><div className="lp-allocation-bar" aria-label="xETH 42%, USDT 34%, Other 24%"><i/><i/><i/></div><dl className="lp-allocation-list"><div><dt><i/>xETH</dt><dd>42%</dd></div><div><dt><i/>USDT</dt><dd>34%</dd></div><div><dt><i/>Other</dt><dd>24%</dd></div></dl></section><section className="lp-custody-boundary"><div><small>Outside Adaptara</small><strong>$14,500</strong></div><div><small>In Vaults</small><strong>$10,500</strong></div></section><p>Nothing moves until you delegate capital.</p></div>;
}

export function VaultConstitutionPreview() {
  const vaults = [["Growth Vault","$4,800","Approval Required"],["Reserve Vault","$3,900","Advisory"],["Opportunity Vault","$1,800","Advisory"]] as const;
  return <div className="lp-product-story lp-vault-story" role="img" aria-label="Three independently governed Vaults and the selected Growth Vault Financial Constitution"><header><div><span>Portfolio</span><strong>$25,000</strong></div><small>$14,500 remains outside Adaptara</small></header><div className="lp-delegation-line"><span>Selected delegated capital</span></div><section className="lp-vault-mini-grid">{vaults.map(([name,value,mode],index)=><article key={name} data-selected={index===0||undefined}><small>{name}</small><strong>{value}</strong><span>{mode}</span></article>)}</section><section className="lp-constitution-mini"><header><div><span>Growth Vault</span><strong>Financial Constitution</strong></div><em>Attention</em></header><dl><div><dt>Minimum reserve</dt><dd>20%</dd></div><div><dt>Maximum asset exposure</dt><dd>50%</dd></div><div><dt>Maximum aggressive</dt><dd>30%</dd></div><div><dt>Daily turnover</dt><dd>10%</dd></div></dl><p>Each Vault has its own rules.</p></section></div>;
}

export function MaraAdaptationPreview() {
  return <div className="lp-product-story lp-mara-story" role="img" aria-label="MARA interpretation, deterministic planning, and a Financial Constitution blocking an unsafe plan"><header><div><span>Growth Vault</span><strong>MARA observation</strong></div><small>Simulation</small></header><p className="lp-mara-observation">xETH exposure is approaching the Vault&apos;s concentration limit.</p><section className="lp-reasoning-steps"><article><small>What changed</small><strong>xETH concentration increased to 47%</strong></article><article><small>Why it matters</small><strong>Maximum permitted exposure is 50%</strong></article><article><small>Recommended direction</small><strong>Reduce concentration risk</strong></article></section><section className="lp-plan-check"><div><small>Deterministic plan</small><span>Projected xETH</span><strong>63%</strong></div><div><small>Financial Constitution</small><span>Maximum</span><strong>50%</strong></div></section><footer><div><small>Constitution outcome</small><strong>BLOCKED</strong></div><p>Nothing moved.<small>No transaction was submitted.</small></p></footer></div>;
}
