"use client";
import { useState } from "react";

export const SHOWCASE_VIEWS = ["Home","Portfolio","Vaults","Activity","Account"] as const;
export type ShowcaseView = typeof SHOWCASE_VIEWS[number];
export const VAULT_FIXTURE_SCENARIOS = ["zero", "v1", "v2", "mixed"] as const;
export type VaultFixtureScenario = typeof VAULT_FIXTURE_SCENARIOS[number];
const metrics = [["Total portfolio","$4,240"],["Managed in Vaults","$1,740"],["Outside Vaults","$2,500"],["Active Vaults","1"]] as const;

export function ProductShowcase({ initialView = "Home" }: { initialView?: ShowcaseView }) {
  const [view,setView] = useState<ShowcaseView>(initialView);
  return <main className="product-fixture"><header><strong>ADAPTARA</strong><nav>{["Home","Portfolio","Vaults","Activity"].map((item)=><button key={item} aria-current={view===item?"page":undefined} onClick={()=>setView(item as ShowcaseView)}>{item}</button>)}</nav><button className="fixture-account" onClick={()=>setView("Account")}>● 0xF327…7813</button></header><div className="fixture-canvas"><div className="fixture-title"><span>Development showcase · deterministic read-only fixture</span><h1>{view === "Home" ? "Overview" : view}</h1><p>{view === "Home" ? "Your wallet, Vault and current Adaptara position." : "Connected fixture state. No signer, transaction API or broadcast."}</p></div>
  {view === "Home" ? <><section className="fixture-metrics">{metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong><small>Fixture data · non-production</small></article>)}</section><section className="fixture-visuals"><article><span>Portfolio allocation</span><div className="fixture-ring"><b>59%</b></div><p>Outside Adaptara 59% · Managed V1 41%</p></article><article><span>Risk exposure</span><h2>Balanced</h2><div className="fixture-bars"><i/><i/><i/></div><p>Reserve 35% · Balanced 50% · Aggressive 15%</p></article><article><span>Constitution</span><h2>Active</h2><dl><div><dt>Reserve minimum</dt><dd>20%</dd></div><div><dt>Single asset maximum</dt><dd>50%</dd></div><div><dt>Max action</dt><dd>10%</dd></div></dl></article></section><section className="fixture-mara"><span>MARA · Market Adaptive Risk Agent</span><h2>Watching your portfolio</h2><p>Your current exposure is Balanced. Reserve remains above the active Vault minimum. MARA cannot sign or move assets.</p><div><button>What is driving my risk?</button><button>Explain my Vault rules</button></div></section><section className="fixture-lower"><article><span>Your Vault</span><h3>Managed Vault V1</h3><strong>$1,740 · Approval Required</strong><p>Constitution active · one Vault permitted by deployed V1</p></article><article><span>Recent activity</span><h3>No verified events yet</h3><p>Adaptara does not invent account history.</p></article></section></> : null}
  {view === "Portfolio" ? <section className="fixture-table"><h2>Your complete X Layer position</h2>{[["xETH","0.82","$2,100","Balanced","Outside Vault"],["USDT","2,140","$2,140","Reserve","Managed + outside"]].map((row)=><div key={row[0]}>{row.map((value)=><span key={value}>{value}</span>)}</div>)}</section> : null}
  {view === "Vaults" ? <section className="fixture-vault"><header><div><span>1 Vault</span><h2>$1,740 managed</h2></div><button disabled>+ Create Vault</button></header><article><h3>Managed Vault V1</h3><strong>Approval Required</strong><p>Constitution Active · independently governed · address authoritative</p></article><aside>Multiple goal-based Vaults require additive V2 architecture.</aside></section> : null}
  {view === "Activity" ? <section className="activity-empty"><span>Verified activity</span><h2>No authoritative activity yet.</h2><p>This fixture intentionally demonstrates the truthful empty state.</p></section> : null}
  {view === "Account" ? <section className="fixture-account-state"><div className="account-dropdown account-dropdown--fixture"><header><i/><div><span>Connected</span><strong>0xF327…7813</strong><small>X Layer Mainnet · read only</small></div></header><button>Copy address</button><a>View on X Layer Explorer</a><button className="account-dropdown__disconnect">Disconnect</button></div></section> : null}
  </div></main>;
}

export function VaultFixtureState({ scenario }: { scenario: VaultFixtureScenario }) {
  const vaults = scenario === "zero" ? [] : scenario === "v1" ? ["V1"] : scenario === "v2" ? ["V2"] : ["V1", "V2", "V2"];
  return <main className="product-fixture"><section className="fixture-vault"><header><div><span>{vaults.length} simulated Vaults</span><h2>{vaults.length ? "Simulated managed value" : "No managed value"}</h2></div><button disabled>+ Create Vault</button></header>{vaults.map((generation, index) => <article key={`${generation}-${index}`}><h3>Managed Vault {generation}{index > 0 ? ` #${index + 1}` : ""}</h3><strong>Read-only fixture</strong><p>Simulated, independently governed, address authoritative.</p></article>)}<aside>{vaults.length ? "Development fixture only; never included in live discovery." : "Multi-Vault infrastructure is live. Creation remains disabled during controlled rollout."}</aside></section></main>;
}
