import { describe, expect, it } from "vitest";
import type { PortfolioSnapshot } from "@/features/portfolio/types";
import { createAssetCatalog } from "@/features/portfolio/catalog";
import { calculateYieldAmounts, projectVaultYield } from "./projection";
import { DEMO_STRSY_TERMS } from "./terms";
const catalog = createAssetCatalog();
const snapshot = (overrides: Partial<PortfolioSnapshot> = {}, balance: bigint | null = 100_000000000000000000n, availability: "available" | "read-error" = "available"): PortfolioSnapshot => ({ source: "vault", accountAddress: "0x0000000000000000000000000000000000000001", chainId: 1952, blockNumber: 10n, blockConsistency: "single-block", capturedAt: "fixture", positions: catalog.map((asset) => ({ asset, availability: asset.id === "strsy" ? availability : "not-configured", rawBalance: asset.id === "strsy" ? balance : null, balanceDecimals: asset.id === "strsy" ? 18 : null, displayBalance: null, referencePrice: null, usdValue: null, usdValueDecimals: 8, allocationBps: null })), totals: { totalUsdValue: 0n, usdValueDecimals: 8, valuedAssetCount: 0, nonzeroAssetCount: balance && balance > 0n ? 1 : 0, unknownBalanceAssetCount: balance === null ? 1 : 0 }, valuationStatus: "unavailable", priceSources: [], ...overrides });

describe("yield projection math", () => {
  it.each([[30, 410958904109589041n, 411776236965681503n, 817332856092462n, 100411776236965681503n], [90, 1232876712328767123n, 1240422483041190792n, 7545770712423669n, 101240422483041190792n], [365, 5000000000000000000n, 5126749646746254853n, 126749646746254853n, 105126749646746254853n]] as const)("returns exact %i-day results", (days, simple, compounded, delta, ending) => expect(calculateYieldAmounts(100_000000000000000000n, 500, days)).toEqual({ simpleYieldRaw: simple, compoundedYieldRaw: compounded, compoundingDeltaVsSimpleRaw: delta, projectedEndingBalanceRaw: ending }));
  it.each([6, 18])("maintains exact identities at %i decimals", (decimals) => { for (const principal of [10n ** BigInt(decimals), 123456789n * 10n ** BigInt(decimals)]) for (const rate of [0, 1, 500, 10_000]) for (const days of [30, 90, 365] as const) { const result = calculateYieldAmounts(principal, rate, days); expect(result.projectedEndingBalanceRaw).toBe(principal + result.compoundedYieldRaw); expect(result.compoundingDeltaVsSimpleRaw).toBe(result.compoundedYieldRaw - result.simpleYieldRaw); expect(result.simpleYieldRaw).toBeGreaterThanOrEqual(0n); expect(result.compoundedYieldRaw).toBeGreaterThanOrEqual(0n); } });
  it("does not manufacture tiny-balance yield", () => expect(calculateYieldAmounts(1n, 500, 365)).toEqual({ simpleYieldRaw: 0n, compoundedYieldRaw: 0n, compoundingDeltaVsSimpleRaw: 0n, projectedEndingBalanceRaw: 1n }));
  it("keeps a negative rounding delta projected without fabricating daily yield", () => { const result = projectVaultYield(snapshot({}, 20n), DEMO_STRSY_TERMS, 365); expect(result.status).toBe("projected"); if (result.status === "projected") { expect(result.projection.simpleYieldRaw).toBeGreaterThan(0n); expect(result.projection.compoundedYieldRaw).toBe(0n); expect(result.projection.compoundingDeltaVsSimpleRaw).toBeLessThan(0n); expect(result.projection.projectedEndingBalanceRaw).toBe(result.projection.principalRaw); } });
});
describe("vault yield eligibility", () => {
  it("projects meaningful canonical vault holdings", () => { const result = projectVaultYield(snapshot(), DEMO_STRSY_TERMS, 30); expect(result.status).toBe("projected"); if (result.status === "projected") expect(result.projection.executionAuthority).toBe("none"); });
  it("rejects forged balance decimals", () => { const input = snapshot(); const position = input.positions.find((item) => item.asset.id === "strsy")!; position.balanceDecimals = 6; expect(projectVaultYield(input, DEMO_STRSY_TERMS, 30).status).toBe("unavailable"); });
  it("rejects forged canonical asset metadata", () => { const input = snapshot(); const position = input.positions.find((item) => item.asset.id === "strsy")!; position.asset = { ...position.asset, symbol: "forged" }; expect(projectVaultYield(input, DEMO_STRSY_TERMS, 30).status).toBe("unavailable"); });
  it("requires single-block portfolio authority", () => expect(projectVaultYield(snapshot({ blockConsistency: "latest-near-simultaneous" }), DEMO_STRSY_TERMS, 30).status).toBe("unavailable"));
  it("rejects duplicate yield-asset positions", () => { const input = snapshot(); const strsy = input.positions.find((item) => item.asset.id === "strsy")!; input.positions = [...input.positions, { ...strsy }]; expect(projectVaultYield(input, DEMO_STRSY_TERMS, 30).status).toBe("unavailable"); });
  it.each([[{ source: "wallet" }, 1n, "available"], [{ chainId: 1 }, 1n, "available"], [{ blockNumber: null }, 1n, "available"], [{}, 0n, "available"], [{}, null, "available"], [{}, 1n, "read-error"]] as const)("fails closed for ineligible context %#", (override, balance, availability) => expect(projectVaultYield(snapshot(override as Partial<PortfolioSnapshot>, balance, availability), DEMO_STRSY_TERMS, 30).status).toBe("unavailable"));
  it("does not mutate authoritative inputs", () => { const input = snapshot(); const before = JSON.stringify(input, (_, value) => typeof value === "bigint" ? value.toString() : value); projectVaultYield(input, DEMO_STRSY_TERMS, 365); expect(JSON.stringify(input, (_, value) => typeof value === "bigint" ? value.toString() : value)).toBe(before); });
});
