"use client";
import {useCallback,useEffect,useRef,useState} from"react";
import{formatEther,getAddress,type Address,type WalletClient}from"viem";
import{useAccount}from"wagmi";
import{WalletControl}from"@/components/wallet/wallet-control";
import{ACCEPT_ADMIN_CALLDATA,acceptGovernanceAdmin,GOVERNANCE_CONTRACTS,governanceBlockReason,governancePublicClient,PRODUCTION_ADMIN,readGovernancePreflight,sessionInvalidationReason,verifyCompletedHandover,type AcceptanceResult,type FinalVerification,type GovernanceRead}from"./handover";
import{createConnectorWalletClient,GovernanceWalletSwitchError,readConnectorReadiness,subscribeToConnectorChanges,switchConnectorToXLayerMainnet,walletReadinessReason,type ObservableProvider}from"./wallet-readiness";

type Step={read?:GovernanceRead;receipt?:AcceptanceResult;loading:boolean;error?:string};const initialSteps=()=>GOVERNANCE_CONTRACTS.map(():Step=>({loading:false}));
export function GovernanceHandover(){
 const{address:wagmiAddress,connector,isConnected}=useAccount();const[actualAddress,setActualAddress]=useState<Address>();const[actualWalletChain,setActualWalletChain]=useState<number>();const[walletClient,setWalletClient]=useState<WalletClient>();const[rpcStatus,setRpcStatus]=useState<"loading"|"healthy"|"unavailable">("loading");const rpcHealthy=rpcStatus==="healthy";const[readinessError,setReadinessError]=useState<string>();const[switchDiagnostic,setSwitchDiagnostic]=useState<string>();const[switching,setSwitching]=useState(false);const[steps,setSteps]=useState(initialSteps);const[stoppedReason,setStoppedReason]=useState<string>();const[finalStatus,setFinalStatus]=useState<FinalVerification|null>(null);const session=useRef<{address:Address;chainId:number}|null>(null);const verifiedCount=steps.findIndex(s=>!s.receipt)===-1?steps.length:steps.findIndex(s=>!s.receipt);
 const refreshWalletReadiness=useCallback(async()=>{setReadinessError(undefined);setWalletClient(undefined);if(!connector){setActualAddress(undefined);setActualWalletChain(undefined);return;}try{const snapshot=await readConnectorReadiness(connector),account=snapshot.accounts[0];setActualAddress(account);setActualWalletChain(snapshot.chainId);if(account&&snapshot.chainId===196)setWalletClient(await createConnectorWalletClient(connector,account));}catch(error){setReadinessError(error instanceof Error?error.message:"Wallet readiness failed.");}},[connector]);
 useEffect(()=>{let active=true;void readGovernancePreflight(governancePublicClient,GOVERNANCE_CONTRACTS[0].address,PRODUCTION_ADMIN).then(read=>{if(!active)return;setSteps(c=>c.map((s,i)=>i===0?{...s,read}:s));setRpcStatus("healthy");}).catch(()=>{if(active)setRpcStatus("unavailable");});return()=>{active=false;};},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void refreshWalletReadiness(),0);return()=>window.clearTimeout(timer);},[refreshWalletReadiness,wagmiAddress]);
 useEffect(()=>{if(!connector)return;let unsubscribe:()=>void=()=>{};void connector.getProvider().then(provider=>{if(provider)unsubscribe=subscribeToConnectorChanges(provider as ObservableProvider,()=>void refreshWalletReadiness());});return()=>unsubscribe();},[connector,refreshWalletReadiness]);
 const refresh=useCallback(async(index:number)=>{if(!actualAddress||actualWalletChain!==196||!rpcHealthy)return;setSteps(c=>c.map((s,i)=>i===index?{...s,loading:true,error:undefined}:s));try{const read=await readGovernancePreflight(governancePublicClient,GOVERNANCE_CONTRACTS[index].address,actualAddress);setSteps(c=>c.map((s,i)=>i===index?{...s,read,loading:false}:s));}catch(error){const message=error instanceof Error?error.message:"Onchain preflight failed.";setSteps(c=>c.map((s,i)=>i===index?{...s,loading:false,error:message}:s));}},[actualAddress,actualWalletChain,rpcHealthy]);
 useEffect(()=>{if(!session.current)return;const reason=sessionInvalidationReason(session.current,{address:actualAddress,chainId:actualWalletChain});if(reason)setStoppedReason(`${reason} Sequence stopped; no automatic retry is allowed.`);},[actualAddress,actualWalletChain]);
 useEffect(()=>{if(verifiedCount>=4||!walletClient)return;const timer=window.setTimeout(()=>void refresh(verifiedCount),0);return()=>window.clearTimeout(timer);},[refresh,verifiedCount,walletClient]);
 const requestSwitch=async()=>{if(!connector){setReadinessError("Connect the production-admin OKX wallet first.");return;}setSwitching(true);setReadinessError(undefined);setSwitchDiagnostic(undefined);setWalletClient(undefined);try{await switchConnectorToXLayerMainnet(connector);await refreshWalletReadiness();}catch(error){setReadinessError("Unable to switch the connected wallet to X Layer Mainnet.");setSwitchDiagnostic(error instanceof GovernanceWalletSwitchError?`${error.method}: ${error.technicalMessage}`:String(error));}finally{setSwitching(false);}};
 const accept=async(index:number)=>{if(!walletClient||!actualAddress||stoppedReason)return;const reason=governanceBlockReason({connected:isConnected,chainId:actualWalletChain,connectedAddress:actualAddress,read:steps[index].read,unlocked:index===verifiedCount,stoppedReason});if(reason)return;session.current??={address:getAddress(actualAddress),chainId:196};setSteps(c=>c.map((s,i)=>i===index?{...s,loading:true,error:undefined}:s));try{const receipt=await acceptGovernanceAdmin({publicClient:governancePublicClient,walletClient,connectedAddress:actualAddress,contract:GOVERNANCE_CONTRACTS[index]});setSteps(c=>c.map((s,i)=>i===index?{...s,receipt,loading:false,read:undefined}:s));}catch(error){const message=error instanceof Error?error.message:"Acceptance stopped.";setStoppedReason(message);setSteps(c=>c.map((s,i)=>i===index?{...s,loading:false,error:message}:s));}};
 useEffect(()=>{if(verifiedCount!==4||finalStatus)return;void verifyCompletedHandover(governancePublicClient).then(setFinalStatus).catch(error=>setFinalStatus({ok:false,failures:[error instanceof Error?error.message:"Final verification failed."],contracts:[]}));},[finalStatus,verifiedCount]);
 return <main style={{maxWidth:960,margin:"0 auto",padding:"48px 24px 80px"}}><p className="eyebrow">Development-only · fixed governance utility</p><h1>Adaptara Production Governance Handover</h1><p>This local screen can request exactly one fixed, zero-value admin-acceptance transaction at a time. It never continues automatically.</p>
 <section className="card" style={{margin:"24px 0",padding:24}}><p><strong>Target chain:</strong> X Layer Mainnet — 196</p><p><strong>Actual wallet chain:</strong> {actualWalletChain??"Unavailable"}</p><p><strong>Read-only RPC:</strong> {rpcStatus==="loading"?"Loading":rpcHealthy?"Healthy · chain 196":"Unavailable"}</p><p><strong>Required signer:</strong> <code>{PRODUCTION_ADMIN}</code></p><p><strong>Connector signer:</strong> <code>{actualAddress??"Not connected"}</code></p><p><strong>Connector client:</strong> {walletClient?"Available":"Unavailable"}</p><WalletControl showNetworkSwitch={false}/>{isConnected&&actualWalletChain!==196?<button type="button" className="button button-secondary" disabled={switching} onClick={()=>void requestSwitch()}>{switching?"Requesting switch…":"Switch to X Layer Mainnet"}</button>:null}{readinessError?<p role="alert" className="wallet-error">{readinessError}</p>:null}{switchDiagnostic?<details><summary>Development diagnostics</summary><code>{switchDiagnostic}</code></details>:null}{stoppedReason?<p role="alert" className="wallet-error"><strong>STOPPED:</strong> {stoppedReason}</p>:null}</section>
 <div style={{display:"grid",gap:16}}>{GOVERNANCE_CONTRACTS.map((contract,index)=>{const step=steps[index],unlocked=index===verifiedCount,readinessReason=walletReadinessReason({address:actualAddress,chainId:actualWalletChain,clientAvailable:Boolean(walletClient),rpcHealthy,switchFailed:Boolean(switchDiagnostic)}),reason=step.receipt?undefined:readinessReason??governanceBlockReason({connected:isConnected,chainId:actualWalletChain,connectedAddress:actualAddress,read:step.read,unlocked,stoppedReason});return <section className="card" style={{padding:24,opacity:index>verifiedCount?.65:1}} key={contract.address}><p className="eyebrow">Contract {index+1} of 4</p><h2>{contract.name}</h2><p><code>{contract.address}</code></p>{step.read?<dl><div><dt>Current admin</dt><dd><code>{step.read.currentAdmin}</code></dd></div><div><dt>Pending admin</dt><dd><code>{step.read.pendingAdmin}</code></dd></div><div><dt>Eligible timestamp</dt><dd>{step.read.acceptSchedule}</dd></div><div><dt>Latest block timestamp</dt><dd>{step.read.blockTimestamp.toString()}</dd></div><div><dt>Native balance</dt><dd>{formatEther(step.read.balance)} OKB</dd></div><div><dt>Function</dt><dd><code>acceptDefaultAdminTransfer()</code></dd></div><div><dt>Calldata</dt><dd><code>{ACCEPT_ADMIN_CALLDATA}</code></dd></div><div><dt>Estimated gas</dt><dd>{step.read.estimatedGas?.toString()??"Simulation failed"}</dd></div><div><dt>Value</dt><dd>0 OKB</dd></div></dl>:null}{step.receipt?<div><p><strong>VERIFIED</strong></p><p>Hash: <code>{step.receipt.hash}</code></p><p>Block: {step.receipt.blockNumber.toString()} · Gas used: {step.receipt.gasUsed.toString()}</p></div>:<><button type="button" className="button button-primary" disabled={Boolean(reason)||step.loading} onClick={()=>void accept(index)}>{step.loading?"Checking…":`Accept ${contract.name} admin`}</button><button type="button" className="button button-secondary" disabled={step.loading||!unlocked||!actualAddress||actualWalletChain!==196||!rpcHealthy} onClick={()=>void refresh(index)}>Refresh preflight</button>{reason?<p className="disabled-explanation">Signing disabled: {reason}</p>:<p>Ready for your explicit wallet confirmation. No transaction starts until you click.</p>}{step.error?<p role="alert" className="wallet-error">{step.error}</p>:null}</>}</section>})}</div>
 {verifiedCount===4?<section className="card" style={{marginTop:24,padding:24}}><h2>Final verification</h2>{!finalStatus?<p>Reading all governance and configuration invariants…</p>:<><div style={{display:"grid",gap:12}}>{finalStatus.contracts.map(c=><article key={c.address}><strong>{c.name}</strong><p><code>{c.address}</code></p><p>Default admin: <code>{c.defaultAdmin}</code></p><p>Pending admin: <code>{c.pendingAdmin}</code></p><p>Runtime bytecode: {c.codePresent?"present":"MISSING"}</p></article>)}</div>{finalStatus.ok?<p><strong>ALL FOUR VERIFIED</strong> — governance changed and protected configuration remains unchanged.</p>:<><p role="alert"><strong>FINAL VERIFICATION FAILED</strong></p><ul>{finalStatus.failures.map(f=><li key={f}>{f}</li>)}</ul></>}</>}</section>:null}</main>;
}
