import{getAddress,type EIP1193Provider}from"viem";import type{Connector}from"wagmi";import{describe,expect,it,vi}from"vitest";import{createConnectorWalletClient,readConnectorReadiness,subscribeToConnectorChanges,switchConnectorToXLayerMainnet,walletReadinessReason}from"./wallet-readiness";
const admin=getAddress("0xf4ac7c9ad5a809240291a4f2e4cbe9189b14cdf4");
function fixture(start=1952){let chain=start;const listeners=new Map<string,Set<(...args:unknown[])=>void>>();const request=vi.fn(async({method}:{method:string})=>{if(method==="eth_chainId")return`0x${chain.toString(16)}`;if(method==="eth_accounts")return[admin];if(method==="wallet_switchEthereumChain"){chain=196;listeners.get("chainChanged")?.forEach(fn=>fn("0xc4"));return null;}throw new Error(`unexpected ${method}`);});const provider={request,on:(event:string,fn:(...args:unknown[])=>void)=>{const set=listeners.get(event)??new Set();set.add(fn);listeners.set(event,set);},removeListener:(event:string,fn:(...args:unknown[])=>void)=>listeners.get(event)?.delete(fn)} as EIP1193Provider&{on:(event:string,fn:(...args:unknown[])=>void)=>void;removeListener:(event:string,fn:(...args:unknown[])=>void)=>void};return{provider,request,connector:{getProvider:vi.fn().mockResolvedValue(provider)} as unknown as Connector,setChain:(value:number)=>{chain=value;listeners.get("chainChanged")?.forEach(fn=>fn(`0x${value.toString(16)}`));}};}
describe("connector-backed governance readiness",()=>{
 it("reports the actual wrong wallet chain",async()=>expect((await readConnectorReadiness(fixture().connector)).chainId).toBe(1952));
 it("requests the switch through the connected provider and detects success",async()=>{const f=fixture();expect((await switchConnectorToXLayerMainnet(f.connector)).chainId).toBe(196);expect(f.request).toHaveBeenCalledWith({method:"wallet_switchEthereumChain",params:[{chainId:"0xc4"}]});});
 it("turns switch rejection or transport failure into a controlled failure",async()=>{const f=fixture();f.request.mockRejectedValueOnce(new TypeError("Failed to fetch"));await expect(switchConnectorToXLayerMainnet(f.connector)).rejects.toMatchObject({message:"Unable to switch the connected wallet to X Layer Mainnet.",method:"wallet_switchEthereumChain"});});
 it("detects a manual wallet switch event",async()=>{const f=fixture();const changed=vi.fn();const stop=subscribeToConnectorChanges(f.provider,changed);f.setChain(196);expect(changed).toHaveBeenCalled();expect((await readConnectorReadiness(f.connector)).chainId).toBe(196);stop();});
 it("distinguishes RPC, account, chain, and connector-client readiness",()=>{expect(walletReadinessReason({address:admin,chainId:1952,clientAvailable:true,rpcHealthy:true})).toMatch(/chain 196/);expect(walletReadinessReason({address:admin,chainId:196,clientAvailable:false,rpcHealthy:true})).toMatch(/client/);expect(walletReadinessReason({address:admin,chainId:196,clientAvailable:true,rpcHealthy:false})).toMatch(/RPC/);expect(walletReadinessReason({address:admin,chainId:196,clientAvailable:true,rpcHealthy:true})).toBeUndefined();});
 it("creates a connector-backed client without invoking any write during readiness",async()=>{const f=fixture(196);const client=await createConnectorWalletClient(f.connector,admin);expect(client.account?.address).toBe(admin);expect(f.request.mock.calls.map(c=>c[0].method)).toEqual(["eth_chainId","eth_accounts"]);expect(f.request).not.toHaveBeenCalledWith(expect.objectContaining({method:"eth_sendTransaction"}));});
 it("failed switching never becomes ready",()=>expect(walletReadinessReason({address:admin,chainId:196,clientAvailable:true,rpcHealthy:true,switchFailed:true})).toMatch(/failed/));
});
