export type HexAddress = `0x${string}`;
export interface PlannerAsset { address: HexAddress; symbol: string; balance: bigint; decimals: number; priceE18: bigint; allocationBps: number; allowed: boolean; reserve: boolean }
export interface DeterministicPlannerInput { vault: HexAddress; chainId: number; proposalId: string; assetIn: PlannerAsset; destination: PlannerAsset; totalValueE18: bigint; targetExposureBps: number; maximumSingleAssetExposureBps: number; maximumActionBps: number; remainingTurnoverBps: number; maximumSlippageBps: number; expiresAt: string }
export interface DeterministicSwapPlan { planId: `0x${string}`; proposalId: string; vault: HexAddress; chainId: number; assetIn: HexAddress; assetOut: HexAddress; amountIn: bigint; amountInValueE18: bigint; currentExposureBps: number; targetExposureBps: number; projectedExposureBps: number; limitingBps: number; remainingTurnoverBps: number; maximumSlippageBps: number; expiresAt: string }
export type PlannerFailure = "PROPOSAL_OUTSIDE_CONSTITUTION" | "ZERO_PORTFOLIO" | "STALE_PROPOSAL" | "UNSUPPORTED_DESTINATION" | "NO_REDUCTION_REQUIRED" | "INSUFFICIENT_BALANCE";
export type PlannerResult = { ok: true; plan: DeterministicSwapPlan } | { ok: false; code: PlannerFailure };
export interface NormalizedSwapRoute { provider: "okx-classic-swap"; chainId: number; assetIn: HexAddress; assetOut: HexAddress; amountIn: bigint; estimatedAmountOut: bigint; minimumAmountOut: bigint; slippageBps: number; priceImpactBps: number | null; router: HexAddress; approvalTarget: HexAddress; recipient: HexAddress; transactionValue: bigint; calldataHash: `0x${string}`; quotedAt: string; expiresAt: string; taxOrHoneypot: boolean }
export interface RouteTrustConfig { chainId: number; routers: readonly HexAddress[]; approvalTargets: readonly HexAddress[]; maximumPriceImpactBps: number }
export interface SwapRouteProvider { getExactInRoute(plan: DeterministicSwapPlan, now: Date): Promise<NormalizedSwapRoute> }
export type ReadinessStatus = "Proposed" | "Planned" | "QuoteValidated" | "ConstitutionValidated" | "SimulationPassed" | "ReadyForApproval" | "ReadyForAdaptiveExecution" | "Blocked" | "Expired";
export interface PreparedAdaptiveExecution { status: ReadinessStatus; proposalId: string; planId: string; vault: HexAddress; chainId: number; routeCommitment: `0x${string}`; route: NormalizedSwapRoute; constitutionPassed: boolean; simulation: { passed: boolean; provider: string; reference: string | null }; executorAddress: HexAddress | null; broadcastAuthorized: false }
export interface TransactionExecutor { address(): Promise<HexAddress>; simulate(execution: PreparedAdaptiveExecution): Promise<{ passed: boolean; reference: string | null }>; broadcast(): Promise<never> }
